#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FlexPieDemo.Droid.Resource", IsApplication=true)]

namespace FlexPieDemo.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Array.cocoaPalette = global::FlexPieDemo.Droid.Resource.Array.cocoaPalette;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Array.coralPalette = global::FlexPieDemo.Droid.Resource.Array.coralPalette;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Array.darkPalette = global::FlexPieDemo.Droid.Resource.Array.darkPalette;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Array.defaultPalette = global::FlexPieDemo.Droid.Resource.Array.defaultPalette;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Array.highConstrastPalette = global::FlexPieDemo.Droid.Resource.Array.highConstrastPalette;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Array.lightPalette = global::FlexPieDemo.Droid.Resource.Array.lightPalette;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Array.midnightPalette = global::FlexPieDemo.Droid.Resource.Array.midnightPalette;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Array.minimalPalette = global::FlexPieDemo.Droid.Resource.Array.minimalPalette;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Array.modernPalette = global::FlexPieDemo.Droid.Resource.Array.modernPalette;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Array.organicPalette = global::FlexPieDemo.Droid.Resource.Array.organicPalette;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Array.slatePalette = global::FlexPieDemo.Droid.Resource.Array.slatePalette;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Attribute.backgroundColor = global::FlexPieDemo.Droid.Resource.Attribute.backgroundColor;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Attribute.borderColor = global::FlexPieDemo.Droid.Resource.Attribute.borderColor;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Attribute.borderWidth = global::FlexPieDemo.Droid.Resource.Attribute.borderWidth;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Attribute.footer = global::FlexPieDemo.Droid.Resource.Attribute.footer;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Attribute.footerFontColor = global::FlexPieDemo.Droid.Resource.Attribute.footerFontColor;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Attribute.footerFontGravity = global::FlexPieDemo.Droid.Resource.Attribute.footerFontGravity;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Attribute.footerFontSize = global::FlexPieDemo.Droid.Resource.Attribute.footerFontSize;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Attribute.footerFontTypeface = global::FlexPieDemo.Droid.Resource.Attribute.footerFontTypeface;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Attribute.footerFontWeight = global::FlexPieDemo.Droid.Resource.Attribute.footerFontWeight;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Attribute.header = global::FlexPieDemo.Droid.Resource.Attribute.header;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Attribute.headerFontColor = global::FlexPieDemo.Droid.Resource.Attribute.headerFontColor;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Attribute.headerFontGravity = global::FlexPieDemo.Droid.Resource.Attribute.headerFontGravity;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Attribute.headerFontSize = global::FlexPieDemo.Droid.Resource.Attribute.headerFontSize;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Attribute.headerFontTypeface = global::FlexPieDemo.Droid.Resource.Attribute.headerFontTypeface;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Attribute.headerFontWeight = global::FlexPieDemo.Droid.Resource.Attribute.headerFontWeight;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Attribute.legend_FontColor = global::FlexPieDemo.Droid.Resource.Attribute.legend_FontColor;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Attribute.legend_FontSize = global::FlexPieDemo.Droid.Resource.Attribute.legend_FontSize;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Attribute.legend_FontTypeface = global::FlexPieDemo.Droid.Resource.Attribute.legend_FontTypeface;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Attribute.legend_FontWeight = global::FlexPieDemo.Droid.Resource.Attribute.legend_FontWeight;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Attribute.legend_backgroundColor = global::FlexPieDemo.Droid.Resource.Attribute.legend_backgroundColor;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Attribute.legend_borderColor = global::FlexPieDemo.Droid.Resource.Attribute.legend_borderColor;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Attribute.legend_borderWidth = global::FlexPieDemo.Droid.Resource.Attribute.legend_borderWidth;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Attribute.palette = global::FlexPieDemo.Droid.Resource.Attribute.palette;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Attribute.plotAreabackgroundColor = global::FlexPieDemo.Droid.Resource.Attribute.plotAreabackgroundColor;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Attribute.ringoFlexChartCore = global::FlexPieDemo.Droid.Resource.Attribute.ringoFlexChartCore;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Attribute.selectedBorderColor = global::FlexPieDemo.Droid.Resource.Attribute.selectedBorderColor;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Attribute.selectedBorderWidth = global::FlexPieDemo.Droid.Resource.Attribute.selectedBorderWidth;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Color.defaultBackgroundColor = global::FlexPieDemo.Droid.Resource.Color.defaultBackgroundColor;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Color.defaultBorderColor = global::FlexPieDemo.Droid.Resource.Color.defaultBorderColor;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Color.defaultFooterFontColor = global::FlexPieDemo.Droid.Resource.Color.defaultFooterFontColor;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Color.defaultHeaderFontColor = global::FlexPieDemo.Droid.Resource.Color.defaultHeaderFontColor;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Color.defaultLegend_FontColor = global::FlexPieDemo.Droid.Resource.Color.defaultLegend_FontColor;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Color.defaultLegend_backgroundColor = global::FlexPieDemo.Droid.Resource.Color.defaultLegend_backgroundColor;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Color.defaultLegend_borderColor = global::FlexPieDemo.Droid.Resource.Color.defaultLegend_borderColor;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Color.defaultPlotAreabackgroundColor = global::FlexPieDemo.Droid.Resource.Color.defaultPlotAreabackgroundColor;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Color.defaultSelectedBorderColor = global::FlexPieDemo.Droid.Resource.Color.defaultSelectedBorderColor;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Dimension.defaultBorderWidth = global::FlexPieDemo.Droid.Resource.Dimension.defaultBorderWidth;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Dimension.defaultFooterFontSize = global::FlexPieDemo.Droid.Resource.Dimension.defaultFooterFontSize;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Dimension.defaultHeaderFontSize = global::FlexPieDemo.Droid.Resource.Dimension.defaultHeaderFontSize;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Dimension.defaultLegend_FontSize = global::FlexPieDemo.Droid.Resource.Dimension.defaultLegend_FontSize;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Dimension.defaultLegend_borderWidth = global::FlexPieDemo.Droid.Resource.Dimension.defaultLegend_borderWidth;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Dimension.defaultSelectedBorderWidth = global::FlexPieDemo.Droid.Resource.Dimension.defaultSelectedBorderWidth;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Drawable.ic_launcher = global::FlexPieDemo.Droid.Resource.Drawable.ic_launcher;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Id.BOLD = global::FlexPieDemo.Droid.Resource.Id.BOLD;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Id.BOLD_ITALIC = global::FlexPieDemo.Droid.Resource.Id.BOLD_ITALIC;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Id.CENTER_HORIZONTAL = global::FlexPieDemo.Droid.Resource.Id.CENTER_HORIZONTAL;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Id.ITALIC = global::FlexPieDemo.Droid.Resource.Id.ITALIC;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Id.LEFT = global::FlexPieDemo.Droid.Resource.Id.LEFT;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Id.NORMAL = global::FlexPieDemo.Droid.Resource.Id.NORMAL;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Id.RIGHT = global::FlexPieDemo.Droid.Resource.Id.RIGHT;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Integer.defaultFooterFontGravity = global::FlexPieDemo.Droid.Resource.Integer.defaultFooterFontGravity;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Integer.defaultFooterFontWeight = global::FlexPieDemo.Droid.Resource.Integer.defaultFooterFontWeight;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Integer.defaultHeaderFontGravity = global::FlexPieDemo.Droid.Resource.Integer.defaultHeaderFontGravity;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Integer.defaultHeaderFontWeight = global::FlexPieDemo.Droid.Resource.Integer.defaultHeaderFontWeight;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Integer.defaultLegend_FontWeight = global::FlexPieDemo.Droid.Resource.Integer.defaultLegend_FontWeight;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.String.ApplicationName = global::FlexPieDemo.Droid.Resource.String.ApplicationName;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.String.Hello = global::FlexPieDemo.Droid.Resource.String.Hello;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.String.app_name = global::FlexPieDemo.Droid.Resource.String.app_name;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.String.defaultFooterFontTypeface = global::FlexPieDemo.Droid.Resource.String.defaultFooterFontTypeface;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.String.defaultHeaderFontTypeface = global::FlexPieDemo.Droid.Resource.String.defaultHeaderFontTypeface;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.String.defaultLegend_FontTypeface = global::FlexPieDemo.Droid.Resource.String.defaultLegend_FontTypeface;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.String.hello_world = global::FlexPieDemo.Droid.Resource.String.hello_world;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Style.AppBaseTheme = global::FlexPieDemo.Droid.Resource.Style.AppBaseTheme;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Style.AppTheme = global::FlexPieDemo.Droid.Resource.Style.AppTheme;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Style.Style_Ringo = global::FlexPieDemo.Droid.Resource.Style.Style_Ringo;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Style.Style_Ringo_FlexChartCore = global::FlexPieDemo.Droid.Resource.Style.Style_Ringo_FlexChartCore;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Style.Style_Ringo_FlexChartCore_Cocoa = global::FlexPieDemo.Droid.Resource.Style.Style_Ringo_FlexChartCore_Cocoa;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Style.Style_Ringo_FlexChartCore_Coral = global::FlexPieDemo.Droid.Resource.Style.Style_Ringo_FlexChartCore_Coral;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Style.Style_Ringo_FlexChartCore_Dark = global::FlexPieDemo.Droid.Resource.Style.Style_Ringo_FlexChartCore_Dark;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Style.Style_Ringo_FlexChartCore_Default = global::FlexPieDemo.Droid.Resource.Style.Style_Ringo_FlexChartCore_Default;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Style.Style_Ringo_FlexChartCore_HighContrast = global::FlexPieDemo.Droid.Resource.Style.Style_Ringo_FlexChartCore_HighContrast;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Style.Style_Ringo_FlexChartCore_Light = global::FlexPieDemo.Droid.Resource.Style.Style_Ringo_FlexChartCore_Light;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Style.Style_Ringo_FlexChartCore_Midnight = global::FlexPieDemo.Droid.Resource.Style.Style_Ringo_FlexChartCore_Midnight;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Style.Style_Ringo_FlexChartCore_Minimal = global::FlexPieDemo.Droid.Resource.Style.Style_Ringo_FlexChartCore_Minimal;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Style.Style_Ringo_FlexChartCore_Modern = global::FlexPieDemo.Droid.Resource.Style.Style_Ringo_FlexChartCore_Modern;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Style.Style_Ringo_FlexChartCore_Organic = global::FlexPieDemo.Droid.Resource.Style.Style_Ringo_FlexChartCore_Organic;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Style.Style_Ringo_FlexChartCore_Slate = global::FlexPieDemo.Droid.Resource.Style.Style_Ringo_FlexChartCore_Slate;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Style.Theme_Ringo_FlexChartCore_Cocoa = global::FlexPieDemo.Droid.Resource.Style.Theme_Ringo_FlexChartCore_Cocoa;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Style.Theme_Ringo_FlexChartCore_Default = global::FlexPieDemo.Droid.Resource.Style.Theme_Ringo_FlexChartCore_Default;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Styleable.FlexChartCore = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Styleable.FlexChartCore_backgroundColor = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_backgroundColor;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Styleable.FlexChartCore_borderColor = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_borderColor;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Styleable.FlexChartCore_borderWidth = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_borderWidth;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Styleable.FlexChartCore_footer = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_footer;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Styleable.FlexChartCore_footerFontColor = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_footerFontColor;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Styleable.FlexChartCore_footerFontGravity = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_footerFontGravity;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Styleable.FlexChartCore_footerFontSize = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_footerFontSize;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Styleable.FlexChartCore_footerFontTypeface = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_footerFontTypeface;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Styleable.FlexChartCore_footerFontWeight = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_footerFontWeight;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Styleable.FlexChartCore_header = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_header;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Styleable.FlexChartCore_headerFontColor = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_headerFontColor;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Styleable.FlexChartCore_headerFontGravity = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_headerFontGravity;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Styleable.FlexChartCore_headerFontSize = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_headerFontSize;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Styleable.FlexChartCore_headerFontTypeface = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_headerFontTypeface;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Styleable.FlexChartCore_headerFontWeight = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_headerFontWeight;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Styleable.FlexChartCore_legend_FontColor = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_legend_FontColor;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Styleable.FlexChartCore_legend_FontSize = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_legend_FontSize;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Styleable.FlexChartCore_legend_FontTypeface = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_legend_FontTypeface;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Styleable.FlexChartCore_legend_FontWeight = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_legend_FontWeight;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Styleable.FlexChartCore_legend_backgroundColor = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_legend_backgroundColor;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Styleable.FlexChartCore_legend_borderColor = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_legend_borderColor;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Styleable.FlexChartCore_legend_borderWidth = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_legend_borderWidth;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Styleable.FlexChartCore_palette = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_palette;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Styleable.FlexChartCore_plotAreabackgroundColor = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_plotAreabackgroundColor;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Styleable.FlexChartCore_selectedBorderColor = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_selectedBorderColor;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Styleable.FlexChartCore_selectedBorderWidth = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_selectedBorderWidth;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Styleable.RingoFlexChartCoreTheme = global::FlexPieDemo.Droid.Resource.Styleable.RingoFlexChartCoreTheme;
			global::Xuni.Xamarin.ChartCore.Render.Android.Resource.Styleable.RingoFlexChartCoreTheme_ringoFlexChartCore = global::FlexPieDemo.Droid.Resource.Styleable.RingoFlexChartCoreTheme_ringoFlexChartCore;
			global::Xuni.Xamarin.Core.Render.Android.Resource.Drawable.default_chart_tooltip = global::FlexPieDemo.Droid.Resource.Drawable.default_chart_tooltip;
			global::Xuni.Xamarin.Core.Render.Android.Resource.Drawable.ic_launcher = global::FlexPieDemo.Droid.Resource.Drawable.ic_launcher;
			global::Xuni.Xamarin.Core.Render.Android.Resource.Id.tooltipContent = global::FlexPieDemo.Droid.Resource.Id.tooltipContent;
			global::Xuni.Xamarin.Core.Render.Android.Resource.Id.tooltipTitle = global::FlexPieDemo.Droid.Resource.Id.tooltipTitle;
			global::Xuni.Xamarin.Core.Render.Android.Resource.Layout.tooltip = global::FlexPieDemo.Droid.Resource.Layout.tooltip;
			global::Xuni.Xamarin.Core.Render.Android.Resource.Raw.globalize_de = global::FlexPieDemo.Droid.Resource.Raw.globalize_de;
			global::Xuni.Xamarin.Core.Render.Android.Resource.Raw.globalize_fr = global::FlexPieDemo.Droid.Resource.Raw.globalize_fr;
			global::Xuni.Xamarin.Core.Render.Android.Resource.Raw.globalize_it = global::FlexPieDemo.Droid.Resource.Raw.globalize_it;
			global::Xuni.Xamarin.Core.Render.Android.Resource.Raw.globalize_ja = global::FlexPieDemo.Droid.Resource.Raw.globalize_ja;
			global::Xuni.Xamarin.Core.Render.Android.Resource.Raw.globalize_ko = global::FlexPieDemo.Droid.Resource.Raw.globalize_ko;
			global::Xuni.Xamarin.Core.Render.Android.Resource.Raw.globalize_pt = global::FlexPieDemo.Droid.Resource.Raw.globalize_pt;
			global::Xuni.Xamarin.Core.Render.Android.Resource.Raw.globalize_ru = global::FlexPieDemo.Droid.Resource.Raw.globalize_ru;
			global::Xuni.Xamarin.Core.Render.Android.Resource.Raw.globalize_zh = global::FlexPieDemo.Droid.Resource.Raw.globalize_zh;
			global::Xuni.Xamarin.Core.Render.Android.Resource.String.ApplicationName = global::FlexPieDemo.Droid.Resource.String.ApplicationName;
			global::Xuni.Xamarin.Core.Render.Android.Resource.String.Hello = global::FlexPieDemo.Droid.Resource.String.Hello;
			global::Xuni.Xamarin.Core.Render.Android.Resource.String.app_name = global::FlexPieDemo.Droid.Resource.String.app_name;
			global::Xuni.Xamarin.Core.Render.Android.Resource.Style.AppBaseTheme = global::FlexPieDemo.Droid.Resource.Style.AppBaseTheme;
			global::Xuni.Xamarin.Core.Render.Android.Resource.Style.AppTheme = global::FlexPieDemo.Droid.Resource.Style.AppTheme;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Array.cocoaPalette = global::FlexPieDemo.Droid.Resource.Array.cocoaPalette;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Array.coralPalette = global::FlexPieDemo.Droid.Resource.Array.coralPalette;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Array.darkPalette = global::FlexPieDemo.Droid.Resource.Array.darkPalette;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Array.defaultPalette = global::FlexPieDemo.Droid.Resource.Array.defaultPalette;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Array.highConstrastPalette = global::FlexPieDemo.Droid.Resource.Array.highConstrastPalette;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Array.lightPalette = global::FlexPieDemo.Droid.Resource.Array.lightPalette;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Array.midnightPalette = global::FlexPieDemo.Droid.Resource.Array.midnightPalette;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Array.minimalPalette = global::FlexPieDemo.Droid.Resource.Array.minimalPalette;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Array.modernPalette = global::FlexPieDemo.Droid.Resource.Array.modernPalette;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Array.organicPalette = global::FlexPieDemo.Droid.Resource.Array.organicPalette;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Array.slatePalette = global::FlexPieDemo.Droid.Resource.Array.slatePalette;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Attribute.backgroundColor = global::FlexPieDemo.Droid.Resource.Attribute.backgroundColor;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Attribute.borderColor = global::FlexPieDemo.Droid.Resource.Attribute.borderColor;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Attribute.borderWidth = global::FlexPieDemo.Droid.Resource.Attribute.borderWidth;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Attribute.footer = global::FlexPieDemo.Droid.Resource.Attribute.footer;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Attribute.footerFontColor = global::FlexPieDemo.Droid.Resource.Attribute.footerFontColor;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Attribute.footerFontGravity = global::FlexPieDemo.Droid.Resource.Attribute.footerFontGravity;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Attribute.footerFontSize = global::FlexPieDemo.Droid.Resource.Attribute.footerFontSize;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Attribute.footerFontTypeface = global::FlexPieDemo.Droid.Resource.Attribute.footerFontTypeface;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Attribute.footerFontWeight = global::FlexPieDemo.Droid.Resource.Attribute.footerFontWeight;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Attribute.header = global::FlexPieDemo.Droid.Resource.Attribute.header;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Attribute.headerFontColor = global::FlexPieDemo.Droid.Resource.Attribute.headerFontColor;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Attribute.headerFontGravity = global::FlexPieDemo.Droid.Resource.Attribute.headerFontGravity;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Attribute.headerFontSize = global::FlexPieDemo.Droid.Resource.Attribute.headerFontSize;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Attribute.headerFontTypeface = global::FlexPieDemo.Droid.Resource.Attribute.headerFontTypeface;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Attribute.headerFontWeight = global::FlexPieDemo.Droid.Resource.Attribute.headerFontWeight;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Attribute.legend_FontColor = global::FlexPieDemo.Droid.Resource.Attribute.legend_FontColor;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Attribute.legend_FontSize = global::FlexPieDemo.Droid.Resource.Attribute.legend_FontSize;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Attribute.legend_FontTypeface = global::FlexPieDemo.Droid.Resource.Attribute.legend_FontTypeface;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Attribute.legend_FontWeight = global::FlexPieDemo.Droid.Resource.Attribute.legend_FontWeight;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Attribute.legend_backgroundColor = global::FlexPieDemo.Droid.Resource.Attribute.legend_backgroundColor;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Attribute.legend_borderColor = global::FlexPieDemo.Droid.Resource.Attribute.legend_borderColor;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Attribute.legend_borderWidth = global::FlexPieDemo.Droid.Resource.Attribute.legend_borderWidth;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Attribute.palette = global::FlexPieDemo.Droid.Resource.Attribute.palette;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Attribute.plotAreabackgroundColor = global::FlexPieDemo.Droid.Resource.Attribute.plotAreabackgroundColor;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Attribute.ringoFlexChartCore = global::FlexPieDemo.Droid.Resource.Attribute.ringoFlexChartCore;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Attribute.ringoFlexPie = global::FlexPieDemo.Droid.Resource.Attribute.ringoFlexPie;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Attribute.selectedBorderColor = global::FlexPieDemo.Droid.Resource.Attribute.selectedBorderColor;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Attribute.selectedBorderWidth = global::FlexPieDemo.Droid.Resource.Attribute.selectedBorderWidth;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Color.defaultBackgroundColor = global::FlexPieDemo.Droid.Resource.Color.defaultBackgroundColor;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Color.defaultBorderColor = global::FlexPieDemo.Droid.Resource.Color.defaultBorderColor;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Color.defaultFooterFontColor = global::FlexPieDemo.Droid.Resource.Color.defaultFooterFontColor;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Color.defaultHeaderFontColor = global::FlexPieDemo.Droid.Resource.Color.defaultHeaderFontColor;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Color.defaultLegend_FontColor = global::FlexPieDemo.Droid.Resource.Color.defaultLegend_FontColor;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Color.defaultLegend_backgroundColor = global::FlexPieDemo.Droid.Resource.Color.defaultLegend_backgroundColor;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Color.defaultLegend_borderColor = global::FlexPieDemo.Droid.Resource.Color.defaultLegend_borderColor;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Color.defaultPlotAreabackgroundColor = global::FlexPieDemo.Droid.Resource.Color.defaultPlotAreabackgroundColor;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Color.defaultSelectedBorderColor = global::FlexPieDemo.Droid.Resource.Color.defaultSelectedBorderColor;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Dimension.defaultBorderWidth = global::FlexPieDemo.Droid.Resource.Dimension.defaultBorderWidth;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Dimension.defaultFooterFontSize = global::FlexPieDemo.Droid.Resource.Dimension.defaultFooterFontSize;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Dimension.defaultHeaderFontSize = global::FlexPieDemo.Droid.Resource.Dimension.defaultHeaderFontSize;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Dimension.defaultLegend_FontSize = global::FlexPieDemo.Droid.Resource.Dimension.defaultLegend_FontSize;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Dimension.defaultLegend_borderWidth = global::FlexPieDemo.Droid.Resource.Dimension.defaultLegend_borderWidth;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Dimension.defaultSelectedBorderWidth = global::FlexPieDemo.Droid.Resource.Dimension.defaultSelectedBorderWidth;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Drawable.default_chart_tooltip = global::FlexPieDemo.Droid.Resource.Drawable.default_chart_tooltip;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Drawable.ic_launcher = global::FlexPieDemo.Droid.Resource.Drawable.ic_launcher;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Id.BOLD = global::FlexPieDemo.Droid.Resource.Id.BOLD;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Id.BOLD_ITALIC = global::FlexPieDemo.Droid.Resource.Id.BOLD_ITALIC;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Id.CENTER_HORIZONTAL = global::FlexPieDemo.Droid.Resource.Id.CENTER_HORIZONTAL;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Id.ITALIC = global::FlexPieDemo.Droid.Resource.Id.ITALIC;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Id.LEFT = global::FlexPieDemo.Droid.Resource.Id.LEFT;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Id.NORMAL = global::FlexPieDemo.Droid.Resource.Id.NORMAL;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Id.RIGHT = global::FlexPieDemo.Droid.Resource.Id.RIGHT;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Id.tooltipContent = global::FlexPieDemo.Droid.Resource.Id.tooltipContent;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Id.tooltipTitle = global::FlexPieDemo.Droid.Resource.Id.tooltipTitle;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Integer.defaultFooterFontGravity = global::FlexPieDemo.Droid.Resource.Integer.defaultFooterFontGravity;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Integer.defaultFooterFontWeight = global::FlexPieDemo.Droid.Resource.Integer.defaultFooterFontWeight;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Integer.defaultHeaderFontGravity = global::FlexPieDemo.Droid.Resource.Integer.defaultHeaderFontGravity;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Integer.defaultHeaderFontWeight = global::FlexPieDemo.Droid.Resource.Integer.defaultHeaderFontWeight;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Integer.defaultLegend_FontWeight = global::FlexPieDemo.Droid.Resource.Integer.defaultLegend_FontWeight;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Layout.tooltip = global::FlexPieDemo.Droid.Resource.Layout.tooltip;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Raw.globalize_de = global::FlexPieDemo.Droid.Resource.Raw.globalize_de;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Raw.globalize_fr = global::FlexPieDemo.Droid.Resource.Raw.globalize_fr;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Raw.globalize_it = global::FlexPieDemo.Droid.Resource.Raw.globalize_it;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Raw.globalize_ja = global::FlexPieDemo.Droid.Resource.Raw.globalize_ja;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Raw.globalize_ko = global::FlexPieDemo.Droid.Resource.Raw.globalize_ko;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Raw.globalize_pt = global::FlexPieDemo.Droid.Resource.Raw.globalize_pt;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Raw.globalize_ru = global::FlexPieDemo.Droid.Resource.Raw.globalize_ru;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Raw.globalize_zh = global::FlexPieDemo.Droid.Resource.Raw.globalize_zh;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.String.ApplicationName = global::FlexPieDemo.Droid.Resource.String.ApplicationName;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.String.Hello = global::FlexPieDemo.Droid.Resource.String.Hello;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.String.app_name = global::FlexPieDemo.Droid.Resource.String.app_name;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.String.defaultFooterFontTypeface = global::FlexPieDemo.Droid.Resource.String.defaultFooterFontTypeface;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.String.defaultHeaderFontTypeface = global::FlexPieDemo.Droid.Resource.String.defaultHeaderFontTypeface;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.String.defaultLegend_FontTypeface = global::FlexPieDemo.Droid.Resource.String.defaultLegend_FontTypeface;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.String.hello_world = global::FlexPieDemo.Droid.Resource.String.hello_world;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Style.AppBaseTheme = global::FlexPieDemo.Droid.Resource.Style.AppBaseTheme;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Style.AppTheme = global::FlexPieDemo.Droid.Resource.Style.AppTheme;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Style.Style_Ringo = global::FlexPieDemo.Droid.Resource.Style.Style_Ringo;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Style.Style_Ringo_FlexChartCore = global::FlexPieDemo.Droid.Resource.Style.Style_Ringo_FlexChartCore;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Style.Style_Ringo_FlexChartCore_Cocoa = global::FlexPieDemo.Droid.Resource.Style.Style_Ringo_FlexChartCore_Cocoa;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Style.Style_Ringo_FlexChartCore_Coral = global::FlexPieDemo.Droid.Resource.Style.Style_Ringo_FlexChartCore_Coral;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Style.Style_Ringo_FlexChartCore_Dark = global::FlexPieDemo.Droid.Resource.Style.Style_Ringo_FlexChartCore_Dark;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Style.Style_Ringo_FlexChartCore_Default = global::FlexPieDemo.Droid.Resource.Style.Style_Ringo_FlexChartCore_Default;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Style.Style_Ringo_FlexChartCore_HighContrast = global::FlexPieDemo.Droid.Resource.Style.Style_Ringo_FlexChartCore_HighContrast;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Style.Style_Ringo_FlexChartCore_Light = global::FlexPieDemo.Droid.Resource.Style.Style_Ringo_FlexChartCore_Light;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Style.Style_Ringo_FlexChartCore_Midnight = global::FlexPieDemo.Droid.Resource.Style.Style_Ringo_FlexChartCore_Midnight;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Style.Style_Ringo_FlexChartCore_Minimal = global::FlexPieDemo.Droid.Resource.Style.Style_Ringo_FlexChartCore_Minimal;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Style.Style_Ringo_FlexChartCore_Modern = global::FlexPieDemo.Droid.Resource.Style.Style_Ringo_FlexChartCore_Modern;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Style.Style_Ringo_FlexChartCore_Organic = global::FlexPieDemo.Droid.Resource.Style.Style_Ringo_FlexChartCore_Organic;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Style.Style_Ringo_FlexChartCore_Slate = global::FlexPieDemo.Droid.Resource.Style.Style_Ringo_FlexChartCore_Slate;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Style.Style_Ringo_FlexPie = global::FlexPieDemo.Droid.Resource.Style.Style_Ringo_FlexPie;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Style.Style_Ringo_FlexPie_Default = global::FlexPieDemo.Droid.Resource.Style.Style_Ringo_FlexPie_Default;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Style.Theme_Ringo_FlexChartCore_Cocoa = global::FlexPieDemo.Droid.Resource.Style.Theme_Ringo_FlexChartCore_Cocoa;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Style.Theme_Ringo_FlexChartCore_Default = global::FlexPieDemo.Droid.Resource.Style.Theme_Ringo_FlexChartCore_Default;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Style.Theme_Ringo_FlexPie_Default = global::FlexPieDemo.Droid.Resource.Style.Theme_Ringo_FlexPie_Default;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Styleable.FlexChartCore = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Styleable.FlexChartCore_backgroundColor = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_backgroundColor;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Styleable.FlexChartCore_borderColor = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_borderColor;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Styleable.FlexChartCore_borderWidth = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_borderWidth;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Styleable.FlexChartCore_footer = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_footer;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Styleable.FlexChartCore_footerFontColor = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_footerFontColor;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Styleable.FlexChartCore_footerFontGravity = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_footerFontGravity;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Styleable.FlexChartCore_footerFontSize = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_footerFontSize;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Styleable.FlexChartCore_footerFontTypeface = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_footerFontTypeface;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Styleable.FlexChartCore_footerFontWeight = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_footerFontWeight;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Styleable.FlexChartCore_header = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_header;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Styleable.FlexChartCore_headerFontColor = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_headerFontColor;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Styleable.FlexChartCore_headerFontGravity = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_headerFontGravity;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Styleable.FlexChartCore_headerFontSize = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_headerFontSize;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Styleable.FlexChartCore_headerFontTypeface = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_headerFontTypeface;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Styleable.FlexChartCore_headerFontWeight = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_headerFontWeight;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Styleable.FlexChartCore_legend_FontColor = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_legend_FontColor;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Styleable.FlexChartCore_legend_FontSize = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_legend_FontSize;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Styleable.FlexChartCore_legend_FontTypeface = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_legend_FontTypeface;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Styleable.FlexChartCore_legend_FontWeight = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_legend_FontWeight;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Styleable.FlexChartCore_legend_backgroundColor = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_legend_backgroundColor;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Styleable.FlexChartCore_legend_borderColor = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_legend_borderColor;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Styleable.FlexChartCore_legend_borderWidth = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_legend_borderWidth;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Styleable.FlexChartCore_palette = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_palette;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Styleable.FlexChartCore_plotAreabackgroundColor = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_plotAreabackgroundColor;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Styleable.FlexChartCore_selectedBorderColor = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_selectedBorderColor;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Styleable.FlexChartCore_selectedBorderWidth = global::FlexPieDemo.Droid.Resource.Styleable.FlexChartCore_selectedBorderWidth;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Styleable.FlexPie = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Styleable.RingoFlexChartCoreTheme = global::FlexPieDemo.Droid.Resource.Styleable.RingoFlexChartCoreTheme;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Styleable.RingoFlexChartCoreTheme_ringoFlexChartCore = global::FlexPieDemo.Droid.Resource.Styleable.RingoFlexChartCoreTheme_ringoFlexChartCore;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Styleable.RingoFlexPieTheme = global::FlexPieDemo.Droid.Resource.Styleable.RingoFlexPieTheme;
			global::Xuni.Xamarin.FlexPie.Render.Android.Resource.Styleable.RingoFlexPieTheme_ringoFlexPie = global::FlexPieDemo.Droid.Resource.Styleable.RingoFlexPieTheme_ringoFlexPie;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f0a0001
			public const int cocoaPalette = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int coralPalette = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int darkPalette = 2131361795;
			
			// aapt resource value: 0x7f0a0000
			public const int defaultPalette = 2131361792;
			
			// aapt resource value: 0x7f0a0004
			public const int highConstrastPalette = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int lightPalette = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int midnightPalette = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int minimalPalette = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int modernPalette = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int organicPalette = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int slatePalette = 2131361802;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000f
			public const int backgroundColor = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int borderColor = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int borderWidth = 2130771985;
			
			// aapt resource value: 0x7f01000b
			public const int footer = 2130771979;
			
			// aapt resource value: 0x7f01000e
			public const int footerFontColor = 2130771982;
			
			// aapt resource value: 0x7f010004
			public const int footerFontGravity = 2130771972;
			
			// aapt resource value: 0x7f01000c
			public const int footerFontSize = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int footerFontTypeface = 2130771981;
			
			// aapt resource value: 0x7f010003
			public const int footerFontWeight = 2130771971;
			
			// aapt resource value: 0x7f010007
			public const int header = 2130771975;
			
			// aapt resource value: 0x7f01000a
			public const int headerFontColor = 2130771978;
			
			// aapt resource value: 0x7f010002
			public const int headerFontGravity = 2130771970;
			
			// aapt resource value: 0x7f010008
			public const int headerFontSize = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int headerFontTypeface = 2130771977;
			
			// aapt resource value: 0x7f010001
			public const int headerFontWeight = 2130771969;
			
			// aapt resource value: 0x7f010018
			public const int legend_FontColor = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int legend_FontSize = 2130771993;
			
			// aapt resource value: 0x7f01001a
			public const int legend_FontTypeface = 2130771994;
			
			// aapt resource value: 0x7f010005
			public const int legend_FontWeight = 2130771973;
			
			// aapt resource value: 0x7f010015
			public const int legend_backgroundColor = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int legend_borderColor = 2130771990;
			
			// aapt resource value: 0x7f010017
			public const int legend_borderWidth = 2130771991;
			
			// aapt resource value: 0x7f010006
			public const int palette = 2130771974;
			
			// aapt resource value: 0x7f010012
			public const int plotAreabackgroundColor = 2130771986;
			
			// aapt resource value: 0x7f01001b
			public const int ringoFlexChartCore = 2130771995;
			
			// aapt resource value: 0x7f010000
			public const int ringoFlexPie = 2130771968;
			
			// aapt resource value: 0x7f010013
			public const int selectedBorderColor = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int selectedBorderWidth = 2130771988;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f090002
			public const int defaultBackgroundColor = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int defaultBorderColor = 2131296259;
			
			// aapt resource value: 0x7f090001
			public const int defaultFooterFontColor = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int defaultHeaderFontColor = 2131296256;
			
			// aapt resource value: 0x7f090008
			public const int defaultLegend_FontColor = 2131296264;
			
			// aapt resource value: 0x7f090006
			public const int defaultLegend_backgroundColor = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int defaultLegend_borderColor = 2131296263;
			
			// aapt resource value: 0x7f090004
			public const int defaultPlotAreabackgroundColor = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int defaultSelectedBorderColor = 2131296261;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070002
			public const int defaultBorderWidth = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int defaultFooterFontSize = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int defaultHeaderFontSize = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int defaultLegend_FontSize = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int defaultLegend_borderWidth = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int defaultSelectedBorderWidth = 2131165187;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int default_chart_tooltip = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_launcher = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b0000
			public const int BOLD = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int BOLD_ITALIC = 2131427329;
			
			// aapt resource value: 0x7f0b0004
			public const int CENTER_HORIZONTAL = 2131427332;
			
			// aapt resource value: 0x7f0b0002
			public const int ITALIC = 2131427330;
			
			// aapt resource value: 0x7f0b0005
			public const int LEFT = 2131427333;
			
			// aapt resource value: 0x7f0b0003
			public const int NORMAL = 2131427331;
			
			// aapt resource value: 0x7f0b0006
			public const int RIGHT = 2131427334;
			
			// aapt resource value: 0x7f0b0008
			public const int tooltipContent = 2131427336;
			
			// aapt resource value: 0x7f0b0007
			public const int tooltipTitle = 2131427335;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080003
			public const int defaultFooterFontGravity = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int defaultFooterFontWeight = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int defaultHeaderFontGravity = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int defaultHeaderFontWeight = 2131230720;
			
			// aapt resource value: 0x7f080004
			public const int defaultLegend_FontWeight = 2131230724;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int tooltip = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int globalize_de = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int globalize_fr = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int globalize_it = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int globalize_ja = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int globalize_ko = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int globalize_pt = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int globalize_ru = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int globalize_zh = 2130968583;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int defaultFooterFontTypeface = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int defaultHeaderFontTypeface = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int defaultLegend_FontTypeface = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int hello_world = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppBaseTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int AppTheme = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int Style_Ringo = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int Style_Ringo_FlexChartCore = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int Style_Ringo_FlexChartCore_Cocoa = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int Style_Ringo_FlexChartCore_Coral = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int Style_Ringo_FlexChartCore_Dark = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int Style_Ringo_FlexChartCore_Default = 2131099655;
			
			// aapt resource value: 0x7f06000b
			public const int Style_Ringo_FlexChartCore_HighContrast = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int Style_Ringo_FlexChartCore_Light = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int Style_Ringo_FlexChartCore_Midnight = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int Style_Ringo_FlexChartCore_Minimal = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int Style_Ringo_FlexChartCore_Modern = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int Style_Ringo_FlexChartCore_Organic = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int Style_Ringo_FlexChartCore_Slate = 2131099665;
			
			// aapt resource value: 0x7f060002
			public const int Style_Ringo_FlexPie = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int Style_Ringo_FlexPie_Default = 2131099651;
			
			// aapt resource value: 0x7f060013
			public const int Theme_Ringo_FlexChartCore_Cocoa = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int Theme_Ringo_FlexChartCore_Default = 2131099666;
			
			// aapt resource value: 0x7f060004
			public const int Theme_Ringo_FlexPie_Default = 2131099652;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FlexChartCore = new int[] {
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994};
			
			// aapt resource value: 14
			public const int FlexChartCore_backgroundColor = 14;
			
			// aapt resource value: 15
			public const int FlexChartCore_borderColor = 15;
			
			// aapt resource value: 16
			public const int FlexChartCore_borderWidth = 16;
			
			// aapt resource value: 10
			public const int FlexChartCore_footer = 10;
			
			// aapt resource value: 13
			public const int FlexChartCore_footerFontColor = 13;
			
			// aapt resource value: 3
			public const int FlexChartCore_footerFontGravity = 3;
			
			// aapt resource value: 11
			public const int FlexChartCore_footerFontSize = 11;
			
			// aapt resource value: 12
			public const int FlexChartCore_footerFontTypeface = 12;
			
			// aapt resource value: 2
			public const int FlexChartCore_footerFontWeight = 2;
			
			// aapt resource value: 6
			public const int FlexChartCore_header = 6;
			
			// aapt resource value: 9
			public const int FlexChartCore_headerFontColor = 9;
			
			// aapt resource value: 1
			public const int FlexChartCore_headerFontGravity = 1;
			
			// aapt resource value: 7
			public const int FlexChartCore_headerFontSize = 7;
			
			// aapt resource value: 8
			public const int FlexChartCore_headerFontTypeface = 8;
			
			// aapt resource value: 0
			public const int FlexChartCore_headerFontWeight = 0;
			
			// aapt resource value: 23
			public const int FlexChartCore_legend_FontColor = 23;
			
			// aapt resource value: 24
			public const int FlexChartCore_legend_FontSize = 24;
			
			// aapt resource value: 25
			public const int FlexChartCore_legend_FontTypeface = 25;
			
			// aapt resource value: 4
			public const int FlexChartCore_legend_FontWeight = 4;
			
			// aapt resource value: 20
			public const int FlexChartCore_legend_backgroundColor = 20;
			
			// aapt resource value: 21
			public const int FlexChartCore_legend_borderColor = 21;
			
			// aapt resource value: 22
			public const int FlexChartCore_legend_borderWidth = 22;
			
			// aapt resource value: 5
			public const int FlexChartCore_palette = 5;
			
			// aapt resource value: 17
			public const int FlexChartCore_plotAreabackgroundColor = 17;
			
			// aapt resource value: 18
			public const int FlexChartCore_selectedBorderColor = 18;
			
			// aapt resource value: 19
			public const int FlexChartCore_selectedBorderWidth = 19;
			
			public static int[] FlexPie;
			
			public static int[] RingoFlexChartCoreTheme = new int[] {
					2130771995};
			
			// aapt resource value: 0
			public const int RingoFlexChartCoreTheme_ringoFlexChartCore = 0;
			
			public static int[] RingoFlexPieTheme = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int RingoFlexPieTheme_ringoFlexPie = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
