#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("GaugeDemo.Android.Resource", IsApplication=true)]

namespace GaugeDemo.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::GaugeDemo.Android.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::GaugeDemo.Android.Resource.String.Hello;
			global::Xuni.Forms.Core.Platform.Android.Resource.Drawable.ic_launcher = global::GaugeDemo.Android.Resource.Drawable.ic_launcher;
			global::Xuni.Forms.Core.Platform.Android.Resource.String.ApplicationName = global::GaugeDemo.Android.Resource.String.ApplicationName;
			global::Xuni.Forms.Core.Platform.Android.Resource.String.Hello = global::GaugeDemo.Android.Resource.String.Hello;
			global::Xuni.Forms.Core.Platform.Android.Resource.Style.AppBaseTheme = global::GaugeDemo.Android.Resource.Style.AppBaseTheme;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_animated = global::GaugeDemo.Android.Resource.Attribute.gauge_animated;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_backgroundColor = global::GaugeDemo.Android.Resource.Attribute.gauge_backgroundColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_bulletBadRangeColor = global::GaugeDemo.Android.Resource.Attribute.gauge_bulletBadRangeColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_bulletBadValue = global::GaugeDemo.Android.Resource.Attribute.gauge_bulletBadValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_bulletGoodRangeColor = global::GaugeDemo.Android.Resource.Attribute.gauge_bulletGoodRangeColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_bulletGoodValue = global::GaugeDemo.Android.Resource.Attribute.gauge_bulletGoodValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_bulletTargetRangeColor = global::GaugeDemo.Android.Resource.Attribute.gauge_bulletTargetRangeColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_bulletTargetValue = global::GaugeDemo.Android.Resource.Attribute.gauge_bulletTargetValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_faceBorderColor = global::GaugeDemo.Android.Resource.Attribute.gauge_faceBorderColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_faceBorderWidth = global::GaugeDemo.Android.Resource.Attribute.gauge_faceBorderWidth;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_faceColor = global::GaugeDemo.Android.Resource.Attribute.gauge_faceColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_format = global::GaugeDemo.Android.Resource.Attribute.gauge_format;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_gaugeWidth = global::GaugeDemo.Android.Resource.Attribute.gauge_gaugeWidth;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_linearGaugeDirection = global::GaugeDemo.Android.Resource.Attribute.gauge_linearGaugeDirection;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_maxFontColor = global::GaugeDemo.Android.Resource.Attribute.gauge_maxFontColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_maxFontSize = global::GaugeDemo.Android.Resource.Attribute.gauge_maxFontSize;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_maxFontTypeFace = global::GaugeDemo.Android.Resource.Attribute.gauge_maxFontTypeFace;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_maxValue = global::GaugeDemo.Android.Resource.Attribute.gauge_maxValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_minFontColor = global::GaugeDemo.Android.Resource.Attribute.gauge_minFontColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_minFontSize = global::GaugeDemo.Android.Resource.Attribute.gauge_minFontSize;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_minFontTypeFace = global::GaugeDemo.Android.Resource.Attribute.gauge_minFontTypeFace;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_minValue = global::GaugeDemo.Android.Resource.Attribute.gauge_minValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_origin = global::GaugeDemo.Android.Resource.Attribute.gauge_origin;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_pointerColor = global::GaugeDemo.Android.Resource.Attribute.gauge_pointerColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_pointerWidth = global::GaugeDemo.Android.Resource.Attribute.gauge_pointerWidth;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_radialStartAngle = global::GaugeDemo.Android.Resource.Attribute.gauge_radialStartAngle;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_radialSweepAngle = global::GaugeDemo.Android.Resource.Attribute.gauge_radialSweepAngle;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_showRanges = global::GaugeDemo.Android.Resource.Attribute.gauge_showRanges;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_showTextType = global::GaugeDemo.Android.Resource.Attribute.gauge_showTextType;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_stepValue = global::GaugeDemo.Android.Resource.Attribute.gauge_stepValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_value = global::GaugeDemo.Android.Resource.Attribute.gauge_value;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_valueFontColor = global::GaugeDemo.Android.Resource.Attribute.gauge_valueFontColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_valueFontSize = global::GaugeDemo.Android.Resource.Attribute.gauge_valueFontSize;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_valueFontTypeFace = global::GaugeDemo.Android.Resource.Attribute.gauge_valueFontTypeFace;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Boolean.defaultAnimated = global::GaugeDemo.Android.Resource.Boolean.defaultAnimated;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Boolean.defaultShowRanges = global::GaugeDemo.Android.Resource.Boolean.defaultShowRanges;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Color.defaultBulletBadRangeColor = global::GaugeDemo.Android.Resource.Color.defaultBulletBadRangeColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Color.defaultBulletGoodRangeColor = global::GaugeDemo.Android.Resource.Color.defaultBulletGoodRangeColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Color.defaultBulletGraphPointerColor = global::GaugeDemo.Android.Resource.Color.defaultBulletGraphPointerColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Color.defaultBulletTargetRangeColor = global::GaugeDemo.Android.Resource.Color.defaultBulletTargetRangeColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Color.defaultFaceColor = global::GaugeDemo.Android.Resource.Color.defaultFaceColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Color.defaultPointerColor = global::GaugeDemo.Android.Resource.Color.defaultPointerColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Dimension.defaultBadValue = global::GaugeDemo.Android.Resource.Dimension.defaultBadValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Dimension.defaultBulletGraphPointerWidth = global::GaugeDemo.Android.Resource.Dimension.defaultBulletGraphPointerWidth;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Dimension.defaultGaugeWidth = global::GaugeDemo.Android.Resource.Dimension.defaultGaugeWidth;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Dimension.defaultGoodValue = global::GaugeDemo.Android.Resource.Dimension.defaultGoodValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Dimension.defaultMaxFontSize = global::GaugeDemo.Android.Resource.Dimension.defaultMaxFontSize;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Dimension.defaultMaxValue = global::GaugeDemo.Android.Resource.Dimension.defaultMaxValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Dimension.defaultMinFontSize = global::GaugeDemo.Android.Resource.Dimension.defaultMinFontSize;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Dimension.defaultMinValue = global::GaugeDemo.Android.Resource.Dimension.defaultMinValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Dimension.defaultOrigin = global::GaugeDemo.Android.Resource.Dimension.defaultOrigin;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Dimension.defaultPointerWidth = global::GaugeDemo.Android.Resource.Dimension.defaultPointerWidth;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Dimension.defaultRadialStartAngle = global::GaugeDemo.Android.Resource.Dimension.defaultRadialStartAngle;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Dimension.defaultRadialSweepAngle = global::GaugeDemo.Android.Resource.Dimension.defaultRadialSweepAngle;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Dimension.defaultStepValue = global::GaugeDemo.Android.Resource.Dimension.defaultStepValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Dimension.defaultTargetValue = global::GaugeDemo.Android.Resource.Dimension.defaultTargetValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Dimension.defaultValue = global::GaugeDemo.Android.Resource.Dimension.defaultValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Dimension.defaultValueFontSize = global::GaugeDemo.Android.Resource.Dimension.defaultValueFontSize;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Drawable.ic_launcher = global::GaugeDemo.Android.Resource.Drawable.ic_launcher;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Id.ALL = global::GaugeDemo.Android.Resource.Id.ALL;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Id.DOWN = global::GaugeDemo.Android.Resource.Id.DOWN;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Id.LEFT = global::GaugeDemo.Android.Resource.Id.LEFT;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Id.MINMAX = global::GaugeDemo.Android.Resource.Id.MINMAX;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Id.NONE = global::GaugeDemo.Android.Resource.Id.NONE;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Id.RIGHT = global::GaugeDemo.Android.Resource.Id.RIGHT;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Id.UP = global::GaugeDemo.Android.Resource.Id.UP;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Id.VALUE = global::GaugeDemo.Android.Resource.Id.VALUE;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Integer.defaultFaceBorderColor = global::GaugeDemo.Android.Resource.Integer.defaultFaceBorderColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Integer.defaultFaceBorderWidth = global::GaugeDemo.Android.Resource.Integer.defaultFaceBorderWidth;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.String.ApplicationName = global::GaugeDemo.Android.Resource.String.ApplicationName;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.String.Hello = global::GaugeDemo.Android.Resource.String.Hello;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.String.app_name = global::GaugeDemo.Android.Resource.String.app_name;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.String.defaultFormat = global::GaugeDemo.Android.Resource.String.defaultFormat;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.String.defaultLinearGaugeDirection = global::GaugeDemo.Android.Resource.String.defaultLinearGaugeDirection;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.String.defaultMaxFontTypeface = global::GaugeDemo.Android.Resource.String.defaultMaxFontTypeface;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.String.defaultMinFontTypeface = global::GaugeDemo.Android.Resource.String.defaultMinFontTypeface;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.String.defaultValueFontTypeface = global::GaugeDemo.Android.Resource.String.defaultValueFontTypeface;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Style.AppBaseTheme = global::GaugeDemo.Android.Resource.Style.AppBaseTheme;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Style.AppTheme = global::GaugeDemo.Android.Resource.Style.AppTheme;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniBulletGraph = global::GaugeDemo.Android.Resource.Styleable.XuniBulletGraph;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniBulletGraph_gauge_bulletBadRangeColor = global::GaugeDemo.Android.Resource.Styleable.XuniBulletGraph_gauge_bulletBadRangeColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniBulletGraph_gauge_bulletBadValue = global::GaugeDemo.Android.Resource.Styleable.XuniBulletGraph_gauge_bulletBadValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniBulletGraph_gauge_bulletGoodRangeColor = global::GaugeDemo.Android.Resource.Styleable.XuniBulletGraph_gauge_bulletGoodRangeColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniBulletGraph_gauge_bulletGoodValue = global::GaugeDemo.Android.Resource.Styleable.XuniBulletGraph_gauge_bulletGoodValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniBulletGraph_gauge_bulletTargetRangeColor = global::GaugeDemo.Android.Resource.Styleable.XuniBulletGraph_gauge_bulletTargetRangeColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniBulletGraph_gauge_bulletTargetValue = global::GaugeDemo.Android.Resource.Styleable.XuniBulletGraph_gauge_bulletTargetValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge = global::GaugeDemo.Android.Resource.Styleable.XuniGauge;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_animated = global::GaugeDemo.Android.Resource.Styleable.XuniGauge_gauge_animated;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_backgroundColor = global::GaugeDemo.Android.Resource.Styleable.XuniGauge_gauge_backgroundColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_faceBorderColor = global::GaugeDemo.Android.Resource.Styleable.XuniGauge_gauge_faceBorderColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_faceBorderWidth = global::GaugeDemo.Android.Resource.Styleable.XuniGauge_gauge_faceBorderWidth;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_faceColor = global::GaugeDemo.Android.Resource.Styleable.XuniGauge_gauge_faceColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_format = global::GaugeDemo.Android.Resource.Styleable.XuniGauge_gauge_format;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_gaugeWidth = global::GaugeDemo.Android.Resource.Styleable.XuniGauge_gauge_gaugeWidth;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_maxFontColor = global::GaugeDemo.Android.Resource.Styleable.XuniGauge_gauge_maxFontColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_maxFontSize = global::GaugeDemo.Android.Resource.Styleable.XuniGauge_gauge_maxFontSize;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_maxFontTypeFace = global::GaugeDemo.Android.Resource.Styleable.XuniGauge_gauge_maxFontTypeFace;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_maxValue = global::GaugeDemo.Android.Resource.Styleable.XuniGauge_gauge_maxValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_minFontColor = global::GaugeDemo.Android.Resource.Styleable.XuniGauge_gauge_minFontColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_minFontSize = global::GaugeDemo.Android.Resource.Styleable.XuniGauge_gauge_minFontSize;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_minFontTypeFace = global::GaugeDemo.Android.Resource.Styleable.XuniGauge_gauge_minFontTypeFace;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_minValue = global::GaugeDemo.Android.Resource.Styleable.XuniGauge_gauge_minValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_origin = global::GaugeDemo.Android.Resource.Styleable.XuniGauge_gauge_origin;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_pointerColor = global::GaugeDemo.Android.Resource.Styleable.XuniGauge_gauge_pointerColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_pointerWidth = global::GaugeDemo.Android.Resource.Styleable.XuniGauge_gauge_pointerWidth;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_showRanges = global::GaugeDemo.Android.Resource.Styleable.XuniGauge_gauge_showRanges;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_showTextType = global::GaugeDemo.Android.Resource.Styleable.XuniGauge_gauge_showTextType;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_stepValue = global::GaugeDemo.Android.Resource.Styleable.XuniGauge_gauge_stepValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_value = global::GaugeDemo.Android.Resource.Styleable.XuniGauge_gauge_value;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_valueFontColor = global::GaugeDemo.Android.Resource.Styleable.XuniGauge_gauge_valueFontColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_valueFontSize = global::GaugeDemo.Android.Resource.Styleable.XuniGauge_gauge_valueFontSize;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_valueFontTypeFace = global::GaugeDemo.Android.Resource.Styleable.XuniGauge_gauge_valueFontTypeFace;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniLinearGauge = global::GaugeDemo.Android.Resource.Styleable.XuniLinearGauge;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniLinearGauge_gauge_linearGaugeDirection = global::GaugeDemo.Android.Resource.Styleable.XuniLinearGauge_gauge_linearGaugeDirection;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniRadialGauge = global::GaugeDemo.Android.Resource.Styleable.XuniRadialGauge;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniRadialGauge_gauge_radialStartAngle = global::GaugeDemo.Android.Resource.Styleable.XuniRadialGauge_gauge_radialStartAngle;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniRadialGauge_gauge_radialSweepAngle = global::GaugeDemo.Android.Resource.Styleable.XuniRadialGauge_gauge_radialSweepAngle;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010018
			public const int gauge_animated = 2130771992;
			
			// aapt resource value: 0x7f010002
			public const int gauge_backgroundColor = 2130771970;
			
			// aapt resource value: 0x7f01001d
			public const int gauge_bulletBadRangeColor = 2130771997;
			
			// aapt resource value: 0x7f01001f
			public const int gauge_bulletBadValue = 2130771999;
			
			// aapt resource value: 0x7f01001c
			public const int gauge_bulletGoodRangeColor = 2130771996;
			
			// aapt resource value: 0x7f010020
			public const int gauge_bulletGoodValue = 2130772000;
			
			// aapt resource value: 0x7f01001e
			public const int gauge_bulletTargetRangeColor = 2130771998;
			
			// aapt resource value: 0x7f010021
			public const int gauge_bulletTargetValue = 2130772001;
			
			// aapt resource value: 0x7f010010
			public const int gauge_faceBorderColor = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int gauge_faceBorderWidth = 2130771985;
			
			// aapt resource value: 0x7f01000e
			public const int gauge_faceColor = 2130771982;
			
			// aapt resource value: 0x7f010013
			public const int gauge_format = 2130771987;
			
			// aapt resource value: 0x7f01000c
			public const int gauge_gaugeWidth = 2130771980;
			
			// aapt resource value: 0x7f010000
			public const int gauge_linearGaugeDirection = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int gauge_maxFontColor = 2130771973;
			
			// aapt resource value: 0x7f010008
			public const int gauge_maxFontSize = 2130771976;
			
			// aapt resource value: 0x7f01000b
			public const int gauge_maxFontTypeFace = 2130771979;
			
			// aapt resource value: 0x7f010015
			public const int gauge_maxValue = 2130771989;
			
			// aapt resource value: 0x7f010004
			public const int gauge_minFontColor = 2130771972;
			
			// aapt resource value: 0x7f010007
			public const int gauge_minFontSize = 2130771975;
			
			// aapt resource value: 0x7f01000a
			public const int gauge_minFontTypeFace = 2130771978;
			
			// aapt resource value: 0x7f010016
			public const int gauge_minValue = 2130771990;
			
			// aapt resource value: 0x7f010012
			public const int gauge_origin = 2130771986;
			
			// aapt resource value: 0x7f01000f
			public const int gauge_pointerColor = 2130771983;
			
			// aapt resource value: 0x7f01000d
			public const int gauge_pointerWidth = 2130771981;
			
			// aapt resource value: 0x7f01001a
			public const int gauge_radialStartAngle = 2130771994;
			
			// aapt resource value: 0x7f01001b
			public const int gauge_radialSweepAngle = 2130771995;
			
			// aapt resource value: 0x7f010019
			public const int gauge_showRanges = 2130771993;
			
			// aapt resource value: 0x7f010001
			public const int gauge_showTextType = 2130771969;
			
			// aapt resource value: 0x7f010017
			public const int gauge_stepValue = 2130771991;
			
			// aapt resource value: 0x7f010014
			public const int gauge_value = 2130771988;
			
			// aapt resource value: 0x7f010003
			public const int gauge_valueFontColor = 2130771971;
			
			// aapt resource value: 0x7f010006
			public const int gauge_valueFontSize = 2130771974;
			
			// aapt resource value: 0x7f010009
			public const int gauge_valueFontTypeFace = 2130771977;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f090000
			public const int defaultAnimated = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int defaultShowRanges = 2131296257;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070004
			public const int defaultBulletBadRangeColor = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int defaultBulletGoodRangeColor = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int defaultBulletGraphPointerColor = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int defaultBulletTargetRangeColor = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int defaultFaceColor = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int defaultPointerColor = 2131165185;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f06000d
			public const int defaultBadValue = 2131099661;
			
			// aapt resource value: 0x7f060005
			public const int defaultBulletGraphPointerWidth = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int defaultGaugeWidth = 2131099651;
			
			// aapt resource value: 0x7f06000e
			public const int defaultGoodValue = 2131099662;
			
			// aapt resource value: 0x7f060002
			public const int defaultMaxFontSize = 2131099650;
			
			// aapt resource value: 0x7f06000a
			public const int defaultMaxValue = 2131099658;
			
			// aapt resource value: 0x7f060001
			public const int defaultMinFontSize = 2131099649;
			
			// aapt resource value: 0x7f06000b
			public const int defaultMinValue = 2131099659;
			
			// aapt resource value: 0x7f060008
			public const int defaultOrigin = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int defaultPointerWidth = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int defaultRadialStartAngle = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int defaultRadialSweepAngle = 2131099655;
			
			// aapt resource value: 0x7f06000c
			public const int defaultStepValue = 2131099660;
			
			// aapt resource value: 0x7f06000f
			public const int defaultTargetValue = 2131099663;
			
			// aapt resource value: 0x7f060009
			public const int defaultValue = 2131099657;
			
			// aapt resource value: 0x7f060000
			public const int defaultValueFontSize = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_camera = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_save = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_launcher = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0004
			public const int ALL = 2131361796;
			
			// aapt resource value: 0x7f0a0000
			public const int DOWN = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int LEFT = 2131361793;
			
			// aapt resource value: 0x7f0a0005
			public const int MINMAX = 2131361797;
			
			// aapt resource value: 0x7f0a0008
			public const int MyButton = 2131361800;
			
			// aapt resource value: 0x7f0a0006
			public const int NONE = 2131361798;
			
			// aapt resource value: 0x7f0a0002
			public const int RIGHT = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int UP = 2131361795;
			
			// aapt resource value: 0x7f0a0007
			public const int VALUE = 2131361799;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080000
			public const int defaultFaceBorderColor = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int defaultFaceBorderWidth = 2131230721;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int defaultFormat = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int defaultLinearGaugeDirection = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int defaultMaxFontTypeface = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int defaultMinFontTypeface = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int defaultValueFontTypeface = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int AppBaseTheme = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int AppTheme = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] XuniBulletGraph = new int[]
			{
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001};
			
			// aapt resource value: 1
			public const int XuniBulletGraph_gauge_bulletBadRangeColor = 1;
			
			// aapt resource value: 3
			public const int XuniBulletGraph_gauge_bulletBadValue = 3;
			
			// aapt resource value: 0
			public const int XuniBulletGraph_gauge_bulletGoodRangeColor = 0;
			
			// aapt resource value: 4
			public const int XuniBulletGraph_gauge_bulletGoodValue = 4;
			
			// aapt resource value: 2
			public const int XuniBulletGraph_gauge_bulletTargetRangeColor = 2;
			
			// aapt resource value: 5
			public const int XuniBulletGraph_gauge_bulletTargetValue = 5;
			
			public static int[] XuniGauge = new int[]
			{
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 23
			public const int XuniGauge_gauge_animated = 23;
			
			// aapt resource value: 1
			public const int XuniGauge_gauge_backgroundColor = 1;
			
			// aapt resource value: 15
			public const int XuniGauge_gauge_faceBorderColor = 15;
			
			// aapt resource value: 16
			public const int XuniGauge_gauge_faceBorderWidth = 16;
			
			// aapt resource value: 13
			public const int XuniGauge_gauge_faceColor = 13;
			
			// aapt resource value: 18
			public const int XuniGauge_gauge_format = 18;
			
			// aapt resource value: 11
			public const int XuniGauge_gauge_gaugeWidth = 11;
			
			// aapt resource value: 4
			public const int XuniGauge_gauge_maxFontColor = 4;
			
			// aapt resource value: 7
			public const int XuniGauge_gauge_maxFontSize = 7;
			
			// aapt resource value: 10
			public const int XuniGauge_gauge_maxFontTypeFace = 10;
			
			// aapt resource value: 20
			public const int XuniGauge_gauge_maxValue = 20;
			
			// aapt resource value: 3
			public const int XuniGauge_gauge_minFontColor = 3;
			
			// aapt resource value: 6
			public const int XuniGauge_gauge_minFontSize = 6;
			
			// aapt resource value: 9
			public const int XuniGauge_gauge_minFontTypeFace = 9;
			
			// aapt resource value: 21
			public const int XuniGauge_gauge_minValue = 21;
			
			// aapt resource value: 17
			public const int XuniGauge_gauge_origin = 17;
			
			// aapt resource value: 14
			public const int XuniGauge_gauge_pointerColor = 14;
			
			// aapt resource value: 12
			public const int XuniGauge_gauge_pointerWidth = 12;
			
			// aapt resource value: 24
			public const int XuniGauge_gauge_showRanges = 24;
			
			// aapt resource value: 0
			public const int XuniGauge_gauge_showTextType = 0;
			
			// aapt resource value: 22
			public const int XuniGauge_gauge_stepValue = 22;
			
			// aapt resource value: 19
			public const int XuniGauge_gauge_value = 19;
			
			// aapt resource value: 2
			public const int XuniGauge_gauge_valueFontColor = 2;
			
			// aapt resource value: 5
			public const int XuniGauge_gauge_valueFontSize = 5;
			
			// aapt resource value: 8
			public const int XuniGauge_gauge_valueFontTypeFace = 8;
			
			public static int[] XuniLinearGauge = new int[]
			{
					2130771968};
			
			// aapt resource value: 0
			public const int XuniLinearGauge_gauge_linearGaugeDirection = 0;
			
			public static int[] XuniRadialGauge = new int[]
			{
					2130771994,
					2130771995};
			
			// aapt resource value: 0
			public const int XuniRadialGauge_gauge_radialStartAngle = 0;
			
			// aapt resource value: 1
			public const int XuniRadialGauge_gauge_radialSweepAngle = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
