#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GaugeDemo.Android.Resource", IsApplication=true)]

namespace GaugeDemo.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Attribute.backgroundColor = global::GaugeDemo.Android.Resource.Attribute.backgroundColor;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Attribute.badRangeColor = global::GaugeDemo.Android.Resource.Attribute.badRangeColor;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Attribute.faceBorderColor = global::GaugeDemo.Android.Resource.Attribute.faceBorderColor;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Attribute.faceBorderWidth = global::GaugeDemo.Android.Resource.Attribute.faceBorderWidth;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Attribute.faceColor = global::GaugeDemo.Android.Resource.Attribute.faceColor;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Attribute.gaughWidth = global::GaugeDemo.Android.Resource.Attribute.gaughWidth;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Attribute.goodRangeColor = global::GaugeDemo.Android.Resource.Attribute.goodRangeColor;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Attribute.maxFontColor = global::GaugeDemo.Android.Resource.Attribute.maxFontColor;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Attribute.maxFontSize = global::GaugeDemo.Android.Resource.Attribute.maxFontSize;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Attribute.maxFontTypeFace = global::GaugeDemo.Android.Resource.Attribute.maxFontTypeFace;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Attribute.minFontColor = global::GaugeDemo.Android.Resource.Attribute.minFontColor;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Attribute.minFontSize = global::GaugeDemo.Android.Resource.Attribute.minFontSize;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Attribute.minFontTypeFace = global::GaugeDemo.Android.Resource.Attribute.minFontTypeFace;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Attribute.pointerColor = global::GaugeDemo.Android.Resource.Attribute.pointerColor;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Attribute.pointerWidth = global::GaugeDemo.Android.Resource.Attribute.pointerWidth;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Attribute.ringoFlexGauge = global::GaugeDemo.Android.Resource.Attribute.ringoFlexGauge;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Attribute.targetRangeColor = global::GaugeDemo.Android.Resource.Attribute.targetRangeColor;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Attribute.valueFontColor = global::GaugeDemo.Android.Resource.Attribute.valueFontColor;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Attribute.valueFontSize = global::GaugeDemo.Android.Resource.Attribute.valueFontSize;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Attribute.valueFontTypeFace = global::GaugeDemo.Android.Resource.Attribute.valueFontTypeFace;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Color.defaultBackgroundColor = global::GaugeDemo.Android.Resource.Color.defaultBackgroundColor;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Color.defaultBadRangeColor = global::GaugeDemo.Android.Resource.Color.defaultBadRangeColor;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Color.defaultFaceColor = global::GaugeDemo.Android.Resource.Color.defaultFaceColor;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Color.defaultGoodRangeColor = global::GaugeDemo.Android.Resource.Color.defaultGoodRangeColor;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Color.defaultMaxFontColor = global::GaugeDemo.Android.Resource.Color.defaultMaxFontColor;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Color.defaultMinFontColor = global::GaugeDemo.Android.Resource.Color.defaultMinFontColor;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Color.defaultPointerColor = global::GaugeDemo.Android.Resource.Color.defaultPointerColor;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Color.defaultTargetRangeColor = global::GaugeDemo.Android.Resource.Color.defaultTargetRangeColor;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Color.defaultValueFontColor = global::GaugeDemo.Android.Resource.Color.defaultValueFontColor;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Dimension.defaultGaughWidth = global::GaugeDemo.Android.Resource.Dimension.defaultGaughWidth;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Dimension.defaultPointerWidth = global::GaugeDemo.Android.Resource.Dimension.defaultPointerWidth;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Drawable.default_chart_tooltip = global::GaugeDemo.Android.Resource.Drawable.default_chart_tooltip;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Drawable.ic_launcher = global::GaugeDemo.Android.Resource.Drawable.ic_launcher;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Id.tooltipContent = global::GaugeDemo.Android.Resource.Id.tooltipContent;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Id.tooltipTitle = global::GaugeDemo.Android.Resource.Id.tooltipTitle;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Integer.defaultFaceBorderColor = global::GaugeDemo.Android.Resource.Integer.defaultFaceBorderColor;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Integer.defaultFaceBorderWidth = global::GaugeDemo.Android.Resource.Integer.defaultFaceBorderWidth;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Integer.defaultMaxFontSize = global::GaugeDemo.Android.Resource.Integer.defaultMaxFontSize;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Integer.defaultMinFontSize = global::GaugeDemo.Android.Resource.Integer.defaultMinFontSize;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Integer.defaultValueFontSize = global::GaugeDemo.Android.Resource.Integer.defaultValueFontSize;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Layout.view_default_render_chart_tooltip = global::GaugeDemo.Android.Resource.Layout.view_default_render_chart_tooltip;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Raw.globalize_de = global::GaugeDemo.Android.Resource.Raw.globalize_de;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Raw.globalize_fr = global::GaugeDemo.Android.Resource.Raw.globalize_fr;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Raw.globalize_it = global::GaugeDemo.Android.Resource.Raw.globalize_it;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Raw.globalize_ja = global::GaugeDemo.Android.Resource.Raw.globalize_ja;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Raw.globalize_ko = global::GaugeDemo.Android.Resource.Raw.globalize_ko;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Raw.globalize_pt = global::GaugeDemo.Android.Resource.Raw.globalize_pt;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Raw.globalize_ru = global::GaugeDemo.Android.Resource.Raw.globalize_ru;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Raw.globalize_zh = global::GaugeDemo.Android.Resource.Raw.globalize_zh;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.String.ApplicationName = global::GaugeDemo.Android.Resource.String.ApplicationName;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.String.Hello = global::GaugeDemo.Android.Resource.String.Hello;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.String.app_name = global::GaugeDemo.Android.Resource.String.app_name;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.String.defaultMaxFontTypeface = global::GaugeDemo.Android.Resource.String.defaultMaxFontTypeface;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.String.defaultMinFontTypeface = global::GaugeDemo.Android.Resource.String.defaultMinFontTypeface;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.String.defaultValueFontTypeface = global::GaugeDemo.Android.Resource.String.defaultValueFontTypeface;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.String.hello_world = global::GaugeDemo.Android.Resource.String.hello_world;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Style.AppBaseTheme = global::GaugeDemo.Android.Resource.Style.AppBaseTheme;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Style.AppTheme = global::GaugeDemo.Android.Resource.Style.AppTheme;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Style.Style_Ringo = global::GaugeDemo.Android.Resource.Style.Style_Ringo;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Style.Style_Ringo_FlexGauge = global::GaugeDemo.Android.Resource.Style.Style_Ringo_FlexGauge;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Style.Style_Ringo_FlexGauge_Default = global::GaugeDemo.Android.Resource.Style.Style_Ringo_FlexGauge_Default;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Style.Theme_Ringo_FlexGauge_Default = global::GaugeDemo.Android.Resource.Style.Theme_Ringo_FlexGauge_Default;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Styleable.FlexGauge = global::GaugeDemo.Android.Resource.Styleable.FlexGauge;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Styleable.FlexGauge_backgroundColor = global::GaugeDemo.Android.Resource.Styleable.FlexGauge_backgroundColor;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Styleable.FlexGauge_badRangeColor = global::GaugeDemo.Android.Resource.Styleable.FlexGauge_badRangeColor;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Styleable.FlexGauge_faceBorderColor = global::GaugeDemo.Android.Resource.Styleable.FlexGauge_faceBorderColor;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Styleable.FlexGauge_faceBorderWidth = global::GaugeDemo.Android.Resource.Styleable.FlexGauge_faceBorderWidth;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Styleable.FlexGauge_faceColor = global::GaugeDemo.Android.Resource.Styleable.FlexGauge_faceColor;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Styleable.FlexGauge_gaughWidth = global::GaugeDemo.Android.Resource.Styleable.FlexGauge_gaughWidth;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Styleable.FlexGauge_goodRangeColor = global::GaugeDemo.Android.Resource.Styleable.FlexGauge_goodRangeColor;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Styleable.FlexGauge_maxFontColor = global::GaugeDemo.Android.Resource.Styleable.FlexGauge_maxFontColor;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Styleable.FlexGauge_maxFontSize = global::GaugeDemo.Android.Resource.Styleable.FlexGauge_maxFontSize;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Styleable.FlexGauge_maxFontTypeFace = global::GaugeDemo.Android.Resource.Styleable.FlexGauge_maxFontTypeFace;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Styleable.FlexGauge_minFontColor = global::GaugeDemo.Android.Resource.Styleable.FlexGauge_minFontColor;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Styleable.FlexGauge_minFontSize = global::GaugeDemo.Android.Resource.Styleable.FlexGauge_minFontSize;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Styleable.FlexGauge_minFontTypeFace = global::GaugeDemo.Android.Resource.Styleable.FlexGauge_minFontTypeFace;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Styleable.FlexGauge_pointerColor = global::GaugeDemo.Android.Resource.Styleable.FlexGauge_pointerColor;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Styleable.FlexGauge_pointerWidth = global::GaugeDemo.Android.Resource.Styleable.FlexGauge_pointerWidth;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Styleable.FlexGauge_targetRangeColor = global::GaugeDemo.Android.Resource.Styleable.FlexGauge_targetRangeColor;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Styleable.FlexGauge_valueFontColor = global::GaugeDemo.Android.Resource.Styleable.FlexGauge_valueFontColor;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Styleable.FlexGauge_valueFontSize = global::GaugeDemo.Android.Resource.Styleable.FlexGauge_valueFontSize;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Styleable.FlexGauge_valueFontTypeFace = global::GaugeDemo.Android.Resource.Styleable.FlexGauge_valueFontTypeFace;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Styleable.RingoFlexGaugeTheme = global::GaugeDemo.Android.Resource.Styleable.RingoFlexGaugeTheme;
			global::Xuni.Xamarin.Gauge.Render.Android.Resource.Styleable.RingoFlexGaugeTheme_ringoFlexGauge = global::GaugeDemo.Android.Resource.Styleable.RingoFlexGaugeTheme_ringoFlexGauge;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int backgroundColor = 2130771968;
			
			// aapt resource value: 0x7f010011
			public const int badRangeColor = 2130771985;
			
			// aapt resource value: 0x7f01000e
			public const int faceBorderColor = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int faceBorderWidth = 2130771983;
			
			// aapt resource value: 0x7f01000c
			public const int faceColor = 2130771980;
			
			// aapt resource value: 0x7f01000a
			public const int gaughWidth = 2130771978;
			
			// aapt resource value: 0x7f010010
			public const int goodRangeColor = 2130771984;
			
			// aapt resource value: 0x7f010003
			public const int maxFontColor = 2130771971;
			
			// aapt resource value: 0x7f010006
			public const int maxFontSize = 2130771974;
			
			// aapt resource value: 0x7f010009
			public const int maxFontTypeFace = 2130771977;
			
			// aapt resource value: 0x7f010002
			public const int minFontColor = 2130771970;
			
			// aapt resource value: 0x7f010005
			public const int minFontSize = 2130771973;
			
			// aapt resource value: 0x7f010008
			public const int minFontTypeFace = 2130771976;
			
			// aapt resource value: 0x7f01000d
			public const int pointerColor = 2130771981;
			
			// aapt resource value: 0x7f01000b
			public const int pointerWidth = 2130771979;
			
			// aapt resource value: 0x7f010013
			public const int ringoFlexGauge = 2130771987;
			
			// aapt resource value: 0x7f010012
			public const int targetRangeColor = 2130771986;
			
			// aapt resource value: 0x7f010001
			public const int valueFontColor = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int valueFontSize = 2130771972;
			
			// aapt resource value: 0x7f010007
			public const int valueFontTypeFace = 2130771975;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070000
			public const int defaultBackgroundColor = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int defaultBadRangeColor = 2131165191;
			
			// aapt resource value: 0x7f070004
			public const int defaultFaceColor = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int defaultGoodRangeColor = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int defaultMaxFontColor = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int defaultMinFontColor = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int defaultPointerColor = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int defaultTargetRangeColor = 2131165192;
			
			// aapt resource value: 0x7f070001
			public const int defaultValueFontColor = 2131165185;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f090000
			public const int defaultGaughWidth = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int defaultPointerWidth = 2131296257;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int default_chart_tooltip = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_launcher = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0000
			public const int MyButton = 2131361792;
			
			// aapt resource value: 0x7f0a0002
			public const int tooltipContent = 2131361794;
			
			// aapt resource value: 0x7f0a0001
			public const int tooltipTitle = 2131361793;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080003
			public const int defaultFaceBorderColor = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int defaultFaceBorderWidth = 2131230724;
			
			// aapt resource value: 0x7f080002
			public const int defaultMaxFontSize = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int defaultMinFontSize = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int defaultValueFontSize = 2131230720;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int view_default_render_chart_tooltip = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int globalize_de = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int globalize_fr = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int globalize_it = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int globalize_ja = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int globalize_ko = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int globalize_pt = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int globalize_ru = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int globalize_zh = 2130968583;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int defaultMaxFontTypeface = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int defaultMinFontTypeface = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int defaultValueFontTypeface = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int hello_world = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppBaseTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int AppTheme = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int Style_Ringo = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int Style_Ringo_FlexGauge = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int Style_Ringo_FlexGauge_Default = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int Theme_Ringo_FlexGauge_Default = 2131099653;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FlexGauge = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986};
			
			// aapt resource value: 0
			public const int FlexGauge_backgroundColor = 0;
			
			// aapt resource value: 17
			public const int FlexGauge_badRangeColor = 17;
			
			// aapt resource value: 14
			public const int FlexGauge_faceBorderColor = 14;
			
			// aapt resource value: 15
			public const int FlexGauge_faceBorderWidth = 15;
			
			// aapt resource value: 12
			public const int FlexGauge_faceColor = 12;
			
			// aapt resource value: 10
			public const int FlexGauge_gaughWidth = 10;
			
			// aapt resource value: 16
			public const int FlexGauge_goodRangeColor = 16;
			
			// aapt resource value: 3
			public const int FlexGauge_maxFontColor = 3;
			
			// aapt resource value: 6
			public const int FlexGauge_maxFontSize = 6;
			
			// aapt resource value: 9
			public const int FlexGauge_maxFontTypeFace = 9;
			
			// aapt resource value: 2
			public const int FlexGauge_minFontColor = 2;
			
			// aapt resource value: 5
			public const int FlexGauge_minFontSize = 5;
			
			// aapt resource value: 8
			public const int FlexGauge_minFontTypeFace = 8;
			
			// aapt resource value: 13
			public const int FlexGauge_pointerColor = 13;
			
			// aapt resource value: 11
			public const int FlexGauge_pointerWidth = 11;
			
			// aapt resource value: 18
			public const int FlexGauge_targetRangeColor = 18;
			
			// aapt resource value: 1
			public const int FlexGauge_valueFontColor = 1;
			
			// aapt resource value: 4
			public const int FlexGauge_valueFontSize = 4;
			
			// aapt resource value: 7
			public const int FlexGauge_valueFontTypeFace = 7;
			
			public static int[] RingoFlexGaugeTheme = new int[] {
					2130771987};
			
			// aapt resource value: 0
			public const int RingoFlexGaugeTheme_ringoFlexGauge = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
