//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexGrid101.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_jp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_jp() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlexGrid101.Resources.AppResources.jp", typeof(AppResources_jp).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   適用 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   折りたたむ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Collapse {
            get {
                return ResourceManager.GetString("Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   列を指定して書式設定する方法を示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnDefinitionDescription {
            get {
                return ResourceManager.GetString("ColumnDefinitionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   列の定義 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnDefinitionTitle {
            get {
                return ResourceManager.GetString("ColumnDefinitionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CellFactory を利用して条件付き書式を設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConditionalFormattingDescription {
            get {
                return ResourceManager.GetString("ConditionalFormattingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   条件付き書式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConditionalFormattingTitle {
            get {
                return ResourceManager.GetString("ConditionalFormattingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ゲージに数値を表示することによってセルをカスタマイズします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CustomCellsDescription {
            get {
                return ResourceManager.GetString("CustomCellsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カスタムセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CustomCellsTitle {
            get {
                return ResourceManager.GetString("CustomCellsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   顧客データの編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditCustomer {
            get {
                return ResourceManager.GetString("EditCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インラインではなく入力フォームによってセルを編集します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditingDescription {
            get {
                return ResourceManager.GetString("EditingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集フォーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditingTitle {
            get {
                return ResourceManager.GetString("EditingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行の編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditRow {
            get {
                return ResourceManager.GetString("EditRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示するビデオはありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EmptyListText {
            get {
                return ResourceManager.GetString("EmptyListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フィルタ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   生成されたフォームから列によってデータをフィルタリングします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterDescription {
            get {
                return ResourceManager.GetString("FilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フィルタリングするテキストを入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterPlaceholderText {
            get {
                return ResourceManager.GetString("FilterPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フィルタ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterTitle {
            get {
                return ResourceManager.GetString("FilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべての列のデータをフィルタリングして強調表示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FullTextFilterDescription {
            get {
                return ResourceManager.GetString("FullTextFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全テキストフィルタ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FullTextFilterTitle {
            get {
                return ResourceManager.GetString("FullTextFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FlexGrid でデータを一度に表示、編集、集計します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GettingStartedDescription {
            get {
                return ResourceManager.GetString("GettingStartedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   はじめに に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GettingStartedTitle {
            get {
                return ResourceManager.GetString("GettingStartedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ビデオのコレクションをグループ化して集計します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GroupingDescription {
            get {
                return ResourceManager.GetString("GroupingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループ化 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GroupingTitle {
            get {
                return ResourceManager.GetString("GroupingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グリッドを下にスクロールしたときにオンデマンドで項目をロードします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OnDemandDescription {
            get {
                return ResourceManager.GetString("OnDemandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オンデマンド に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OnDemandTitle {
            get {
                return ResourceManager.GetString("OnDemandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フィルタを解除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YouTube で検索するビデオのテキストを入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SearchPlaceholderText {
            get {
                return ResourceManager.GetString("SearchPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   各種セル選択モードを示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectionModesDescription {
            get {
                return ResourceManager.GetString("SelectionModesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択モード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectionModesTitle {
            get {
                return ResourceManager.GetString("SelectionModesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ソート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
    }
}
