//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexGrid101.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlexGrid101.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        internal static string Collapse {
            get {
                return ResourceManager.GetString("Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to specify and format columns..
        /// </summary>
        internal static string ColumnDefinitionDescription {
            get {
                return ResourceManager.GetString("ColumnDefinitionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Definitions.
        /// </summary>
        internal static string ColumnDefinitionTitle {
            get {
                return ResourceManager.GetString("ColumnDefinitionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses a CellFactory to apply conditional formatting..
        /// </summary>
        internal static string ConditionalFormattingDescription {
            get {
                return ResourceManager.GetString("ConditionalFormattingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditional Formatting.
        /// </summary>
        internal static string ConditionalFormattingTitle {
            get {
                return ResourceManager.GetString("ConditionalFormattingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customizes a cell by displaying a numeric value in a gauge..
        /// </summary>
        internal static string CustomCellsDescription {
            get {
                return ResourceManager.GetString("CustomCellsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Cells.
        /// </summary>
        internal static string CustomCellsTitle {
            get {
                return ResourceManager.GetString("CustomCellsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Customer.
        /// </summary>
        internal static string EditCustomer {
            get {
                return ResourceManager.GetString("EditCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit cells by input form rather than inline..
        /// </summary>
        internal static string EditingDescription {
            get {
                return ResourceManager.GetString("EditingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing Form.
        /// </summary>
        internal static string EditingTitle {
            get {
                return ResourceManager.GetString("EditingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Row.
        /// </summary>
        internal static string EditRow {
            get {
                return ResourceManager.GetString("EditRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no videos to show..
        /// </summary>
        internal static string EmptyListText {
            get {
                return ResourceManager.GetString("EmptyListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters the data by columns through a generated form..
        /// </summary>
        internal static string FilterDescription {
            get {
                return ResourceManager.GetString("FilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text to filter.
        /// </summary>
        internal static string FilterPlaceholderText {
            get {
                return ResourceManager.GetString("FilterPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string FilterTitle {
            get {
                return ResourceManager.GetString("FilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters and highlights the data across all columns..
        /// </summary>
        internal static string FullTextFilterDescription {
            get {
                return ResourceManager.GetString("FullTextFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Text Filter.
        /// </summary>
        internal static string FullTextFilterTitle {
            get {
                return ResourceManager.GetString("FullTextFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display, edit and aggregate your data all at once with FlexGrid..
        /// </summary>
        internal static string GettingStartedDescription {
            get {
                return ResourceManager.GetString("GettingStartedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Started.
        /// </summary>
        internal static string GettingStartedTitle {
            get {
                return ResourceManager.GetString("GettingStartedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups and aggregates a collection of videos..
        /// </summary>
        internal static string GroupingDescription {
            get {
                return ResourceManager.GetString("GroupingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping.
        /// </summary>
        internal static string GroupingTitle {
            get {
                return ResourceManager.GetString("GroupingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load items on demand as the user scrolls down the grid..
        /// </summary>
        internal static string OnDemandDescription {
            get {
                return ResourceManager.GetString("OnDemandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Demand.
        /// </summary>
        internal static string OnDemandTitle {
            get {
                return ResourceManager.GetString("OnDemandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text to search videos on YouTube.
        /// </summary>
        internal static string SearchPlaceholderText {
            get {
                return ResourceManager.GetString("SearchPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the various cell selection modes..
        /// </summary>
        internal static string SelectionModesDescription {
            get {
                return ResourceManager.GetString("SelectionModesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Modes.
        /// </summary>
        internal static string SelectionModesTitle {
            get {
                return ResourceManager.GetString("SelectionModesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        internal static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
    }
}
