//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gauges101.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_jp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_jp() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gauges101.Resources.AppResources.jp", typeof(AppResources_jp).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   カスタムのアニメーション手法を示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AnimationDescription {
            get {
                return ResourceManager.GetString("AnimationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アニメーション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AnimationTitle {
            get {
                return ResourceManager.GetString("AnimationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   角度が異なる放射状ゲージを示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutomaticScalingDescription {
            get {
                return ResourceManager.GetString("AutomaticScalingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動スケーリング に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutomaticScalingTitle {
            get {
                return ResourceManager.GetString("AutomaticScalingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「良い」、「悪い」、「目標」の範囲が設定されたブレットグラフを示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BulletGraphDescription {
            get {
                return ResourceManager.GetString("BulletGraphDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブレットグラフ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BulletGraphTitle {
            get {
                return ResourceManager.GetString("BulletGraphTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   方向が異なる線形ゲージを示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirectionDescription {
            get {
                return ResourceManager.GetString("DirectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   方向 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirectionTitle {
            get {
                return ResourceManager.GetString("DirectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値ラベルをゲージに表示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DisplayingValuesDescription {
            get {
                return ResourceManager.GetString("DisplayingValuesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値の表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DisplayingValuesTitle {
            get {
                return ResourceManager.GetString("DisplayingValuesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ゲージの画像をエクスポートする方法を示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExportImageDescription {
            get {
                return ResourceManager.GetString("ExportImageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像のエクスポート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExportImageTitle {
            get {
                return ResourceManager.GetString("ExportImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インタラクション機能を持つシンプルなゲージコントロールを示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GettingStartedDescription {
            get {
                return ResourceManager.GetString("GettingStartedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   はじめに に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GettingStartedTitle {
            get {
                return ResourceManager.GetString("GettingStartedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カスタマイズされた範囲をポインタの背後に表示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UsingRangesDescription {
            get {
                return ResourceManager.GetString("UsingRangesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   範囲の使用 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UsingRangesTitle {
            get {
                return ResourceManager.GetString("UsingRangesTitle", resourceCulture);
            }
        }
    }
}
