#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("FlexGrid101.Android.Resource", IsApplication=true)]

namespace FlexGrid101.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::FlexGrid101.Android.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::FlexGrid101.Android.Resource.String.Hello;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.allowSorting = global::FlexGrid101.Android.Resource.Attribute.allowSorting;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.alternatingRowBackgroundColor = global::FlexGrid101.Android.Resource.Attribute.alternatingRowBackgroundColor;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.autoGenerateColumns = global::FlexGrid101.Android.Resource.Attribute.autoGenerateColumns;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.borderColor = global::FlexGrid101.Android.Resource.Attribute.borderColor;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.borderWidth = global::FlexGrid101.Android.Resource.Attribute.borderWidth;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.cellBackgroundColor = global::FlexGrid101.Android.Resource.Attribute.cellBackgroundColor;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.cellPaddingBottom = global::FlexGrid101.Android.Resource.Attribute.cellPaddingBottom;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.cellPaddingLeft = global::FlexGrid101.Android.Resource.Attribute.cellPaddingLeft;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.cellPaddingRight = global::FlexGrid101.Android.Resource.Attribute.cellPaddingRight;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.cellPaddingTop = global::FlexGrid101.Android.Resource.Attribute.cellPaddingTop;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.columnHeaderBackgroundColor = global::FlexGrid101.Android.Resource.Attribute.columnHeaderBackgroundColor;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.columnHeaderFontColor = global::FlexGrid101.Android.Resource.Attribute.columnHeaderFontColor;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.columnHeaderFontSize = global::FlexGrid101.Android.Resource.Attribute.columnHeaderFontSize;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.columnHeaderFontTypeface = global::FlexGrid101.Android.Resource.Attribute.columnHeaderFontTypeface;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.columnHeaderFontWeight = global::FlexGrid101.Android.Resource.Attribute.columnHeaderFontWeight;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.fontColor = global::FlexGrid101.Android.Resource.Attribute.fontColor;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.fontSize = global::FlexGrid101.Android.Resource.Attribute.fontSize;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.fontTypeface = global::FlexGrid101.Android.Resource.Attribute.fontTypeface;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.fontWeight = global::FlexGrid101.Android.Resource.Attribute.fontWeight;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.gridLinesColor = global::FlexGrid101.Android.Resource.Attribute.gridLinesColor;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.gridLinesVisibility = global::FlexGrid101.Android.Resource.Attribute.gridLinesVisibility;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.gridLinesWidth = global::FlexGrid101.Android.Resource.Attribute.gridLinesWidth;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.groupHeaderFormat = global::FlexGrid101.Android.Resource.Attribute.groupHeaderFormat;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.groupRowBackgroundColor = global::FlexGrid101.Android.Resource.Attribute.groupRowBackgroundColor;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.groupRowFontColor = global::FlexGrid101.Android.Resource.Attribute.groupRowFontColor;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.headerGridLinesColor = global::FlexGrid101.Android.Resource.Attribute.headerGridLinesColor;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.headersVisibility = global::FlexGrid101.Android.Resource.Attribute.headersVisibility;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.readOnly = global::FlexGrid101.Android.Resource.Attribute.readOnly;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.rowHeaderBackgroundColor = global::FlexGrid101.Android.Resource.Attribute.rowHeaderBackgroundColor;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.rowHeaderFontColor = global::FlexGrid101.Android.Resource.Attribute.rowHeaderFontColor;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.rowHeaderFontSize = global::FlexGrid101.Android.Resource.Attribute.rowHeaderFontSize;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.rowHeaderFontTypeface = global::FlexGrid101.Android.Resource.Attribute.rowHeaderFontTypeface;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.rowHeaderFontWeight = global::FlexGrid101.Android.Resource.Attribute.rowHeaderFontWeight;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.selectionAdornerBorderColor = global::FlexGrid101.Android.Resource.Attribute.selectionAdornerBorderColor;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.selectionAdornerColor = global::FlexGrid101.Android.Resource.Attribute.selectionAdornerColor;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.selectionBackgroundColor = global::FlexGrid101.Android.Resource.Attribute.selectionBackgroundColor;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.selectionFontColor = global::FlexGrid101.Android.Resource.Attribute.selectionFontColor;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.selectionMode = global::FlexGrid101.Android.Resource.Attribute.selectionMode;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.showGroups = global::FlexGrid101.Android.Resource.Attribute.showGroups;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Attribute.showSort = global::FlexGrid101.Android.Resource.Attribute.showSort;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Color.filter_view_background = global::FlexGrid101.Android.Resource.Color.filter_view_background;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Color.filter_view_text = global::FlexGrid101.Android.Resource.Color.filter_view_text;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Dimension.activity_horizontal_margin = global::FlexGrid101.Android.Resource.Dimension.activity_horizontal_margin;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Dimension.activity_vertical_margin = global::FlexGrid101.Android.Resource.Dimension.activity_vertical_margin;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Dimension.defaultCellPaddingBottom = global::FlexGrid101.Android.Resource.Dimension.defaultCellPaddingBottom;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Dimension.defaultCellPaddingLeft = global::FlexGrid101.Android.Resource.Dimension.defaultCellPaddingLeft;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Dimension.defaultCellPaddingRight = global::FlexGrid101.Android.Resource.Dimension.defaultCellPaddingRight;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Dimension.defaultCellPaddingTop = global::FlexGrid101.Android.Resource.Dimension.defaultCellPaddingTop;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Dimension.defaultFontSize = global::FlexGrid101.Android.Resource.Dimension.defaultFontSize;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Drawable.ic_launcher = global::FlexGrid101.Android.Resource.Drawable.ic_launcher;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Id.ALL = global::FlexGrid101.Android.Resource.Id.ALL;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Id.BOLD = global::FlexGrid101.Android.Resource.Id.BOLD;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Id.BOLD_ITALIC = global::FlexGrid101.Android.Resource.Id.BOLD_ITALIC;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Id.CELL = global::FlexGrid101.Android.Resource.Id.CELL;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Id.CELL_RANGE = global::FlexGrid101.Android.Resource.Id.CELL_RANGE;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Id.COLUMN = global::FlexGrid101.Android.Resource.Id.COLUMN;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Id.ITALIC = global::FlexGrid101.Android.Resource.Id.ITALIC;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Id.NONE = global::FlexGrid101.Android.Resource.Id.NONE;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Id.NORMAL = global::FlexGrid101.Android.Resource.Id.NORMAL;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Id.ROW = global::FlexGrid101.Android.Resource.Id.ROW;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Id.ROW_RANGE = global::FlexGrid101.Android.Resource.Id.ROW_RANGE;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Integer.defaultCellFontGravity = global::FlexGrid101.Android.Resource.Integer.defaultCellFontGravity;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Integer.defaultCellFontWeight = global::FlexGrid101.Android.Resource.Integer.defaultCellFontWeight;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.String.ApplicationName = global::FlexGrid101.Android.Resource.String.ApplicationName;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.String.Hello = global::FlexGrid101.Android.Resource.String.Hello;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.String.app_name = global::FlexGrid101.Android.Resource.String.app_name;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.String.defaultCellFontTypeface = global::FlexGrid101.Android.Resource.String.defaultCellFontTypeface;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.String.filter_view_ascending = global::FlexGrid101.Android.Resource.String.filter_view_ascending;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.String.filter_view_clear = global::FlexGrid101.Android.Resource.String.filter_view_clear;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.String.filter_view_descending = global::FlexGrid101.Android.Resource.String.filter_view_descending;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.String.filter_view_done = global::FlexGrid101.Android.Resource.String.filter_view_done;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.String.filter_view_select_all = global::FlexGrid101.Android.Resource.String.filter_view_select_all;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.String.groupHeaderFormat = global::FlexGrid101.Android.Resource.String.groupHeaderFormat;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Style.AppBaseTheme = global::FlexGrid101.Android.Resource.Style.AppBaseTheme;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Style.AppTheme = global::FlexGrid101.Android.Resource.Style.AppTheme;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid = global::FlexGrid101.Android.Resource.Styleable.FlexGrid;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_allowSorting = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_allowSorting;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_alternatingRowBackgroundColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_alternatingRowBackgroundColor;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_autoGenerateColumns = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_autoGenerateColumns;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_borderColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_borderColor;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_borderWidth = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_borderWidth;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_cellBackgroundColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_cellBackgroundColor;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_cellPaddingBottom = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_cellPaddingBottom;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_cellPaddingLeft = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_cellPaddingLeft;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_cellPaddingRight = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_cellPaddingRight;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_cellPaddingTop = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_cellPaddingTop;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_columnHeaderBackgroundColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_columnHeaderBackgroundColor;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_columnHeaderFontColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_columnHeaderFontColor;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_columnHeaderFontSize = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_columnHeaderFontSize;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_columnHeaderFontTypeface = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_columnHeaderFontTypeface;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_columnHeaderFontWeight = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_columnHeaderFontWeight;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_fontColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_fontColor;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_fontSize = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_fontSize;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_fontTypeface = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_fontTypeface;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_fontWeight = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_fontWeight;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_gridLinesColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_gridLinesColor;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_gridLinesVisibility = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_gridLinesVisibility;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_gridLinesWidth = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_gridLinesWidth;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_groupHeaderFormat = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_groupHeaderFormat;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_groupRowBackgroundColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_groupRowBackgroundColor;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_groupRowFontColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_groupRowFontColor;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_headerGridLinesColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_headerGridLinesColor;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_headersVisibility = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_headersVisibility;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_readOnly = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_readOnly;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_rowHeaderBackgroundColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_rowHeaderBackgroundColor;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_rowHeaderFontColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_rowHeaderFontColor;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_rowHeaderFontSize = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_rowHeaderFontSize;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_rowHeaderFontTypeface = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_rowHeaderFontTypeface;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_rowHeaderFontWeight = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_rowHeaderFontWeight;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_selectionAdornerBorderColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_selectionAdornerBorderColor;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_selectionAdornerColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_selectionAdornerColor;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_selectionBackgroundColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_selectionBackgroundColor;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_selectionFontColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_selectionFontColor;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_selectionMode = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_selectionMode;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_showGroups = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_showGroups;
			global::Xuni.Forms.FlexGrid.Platform.Android.Resource.Styleable.FlexGrid_showSort = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_showSort;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_animated = global::FlexGrid101.Android.Resource.Attribute.gauge_animated;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_backgroundColor = global::FlexGrid101.Android.Resource.Attribute.gauge_backgroundColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_bulletBadRangeColor = global::FlexGrid101.Android.Resource.Attribute.gauge_bulletBadRangeColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_bulletBadValue = global::FlexGrid101.Android.Resource.Attribute.gauge_bulletBadValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_bulletGoodRangeColor = global::FlexGrid101.Android.Resource.Attribute.gauge_bulletGoodRangeColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_bulletGoodValue = global::FlexGrid101.Android.Resource.Attribute.gauge_bulletGoodValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_bulletTargetRangeColor = global::FlexGrid101.Android.Resource.Attribute.gauge_bulletTargetRangeColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_bulletTargetValue = global::FlexGrid101.Android.Resource.Attribute.gauge_bulletTargetValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_faceBorderColor = global::FlexGrid101.Android.Resource.Attribute.gauge_faceBorderColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_faceBorderWidth = global::FlexGrid101.Android.Resource.Attribute.gauge_faceBorderWidth;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_faceColor = global::FlexGrid101.Android.Resource.Attribute.gauge_faceColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_format = global::FlexGrid101.Android.Resource.Attribute.gauge_format;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_gaugeWidth = global::FlexGrid101.Android.Resource.Attribute.gauge_gaugeWidth;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_linearGaugeDirection = global::FlexGrid101.Android.Resource.Attribute.gauge_linearGaugeDirection;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_maxFontColor = global::FlexGrid101.Android.Resource.Attribute.gauge_maxFontColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_maxFontSize = global::FlexGrid101.Android.Resource.Attribute.gauge_maxFontSize;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_maxFontTypeFace = global::FlexGrid101.Android.Resource.Attribute.gauge_maxFontTypeFace;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_maxValue = global::FlexGrid101.Android.Resource.Attribute.gauge_maxValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_minFontColor = global::FlexGrid101.Android.Resource.Attribute.gauge_minFontColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_minFontSize = global::FlexGrid101.Android.Resource.Attribute.gauge_minFontSize;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_minFontTypeFace = global::FlexGrid101.Android.Resource.Attribute.gauge_minFontTypeFace;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_minValue = global::FlexGrid101.Android.Resource.Attribute.gauge_minValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_origin = global::FlexGrid101.Android.Resource.Attribute.gauge_origin;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_pointerColor = global::FlexGrid101.Android.Resource.Attribute.gauge_pointerColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_pointerWidth = global::FlexGrid101.Android.Resource.Attribute.gauge_pointerWidth;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_radialStartAngle = global::FlexGrid101.Android.Resource.Attribute.gauge_radialStartAngle;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_radialSweepAngle = global::FlexGrid101.Android.Resource.Attribute.gauge_radialSweepAngle;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_showRanges = global::FlexGrid101.Android.Resource.Attribute.gauge_showRanges;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_showTextType = global::FlexGrid101.Android.Resource.Attribute.gauge_showTextType;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_stepValue = global::FlexGrid101.Android.Resource.Attribute.gauge_stepValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_value = global::FlexGrid101.Android.Resource.Attribute.gauge_value;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_valueFontColor = global::FlexGrid101.Android.Resource.Attribute.gauge_valueFontColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_valueFontSize = global::FlexGrid101.Android.Resource.Attribute.gauge_valueFontSize;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Attribute.gauge_valueFontTypeFace = global::FlexGrid101.Android.Resource.Attribute.gauge_valueFontTypeFace;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Boolean.defaultAnimated = global::FlexGrid101.Android.Resource.Boolean.defaultAnimated;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Boolean.defaultShowRanges = global::FlexGrid101.Android.Resource.Boolean.defaultShowRanges;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Color.defaultBulletBadRangeColor = global::FlexGrid101.Android.Resource.Color.defaultBulletBadRangeColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Color.defaultBulletGoodRangeColor = global::FlexGrid101.Android.Resource.Color.defaultBulletGoodRangeColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Color.defaultBulletGraphPointerColor = global::FlexGrid101.Android.Resource.Color.defaultBulletGraphPointerColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Color.defaultBulletTargetRangeColor = global::FlexGrid101.Android.Resource.Color.defaultBulletTargetRangeColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Color.defaultFaceColor = global::FlexGrid101.Android.Resource.Color.defaultFaceColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Color.defaultPointerColor = global::FlexGrid101.Android.Resource.Color.defaultPointerColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Dimension.defaultBadValue = global::FlexGrid101.Android.Resource.Dimension.defaultBadValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Dimension.defaultBulletGraphPointerWidth = global::FlexGrid101.Android.Resource.Dimension.defaultBulletGraphPointerWidth;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Dimension.defaultGaugeWidth = global::FlexGrid101.Android.Resource.Dimension.defaultGaugeWidth;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Dimension.defaultGoodValue = global::FlexGrid101.Android.Resource.Dimension.defaultGoodValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Dimension.defaultMaxFontSize = global::FlexGrid101.Android.Resource.Dimension.defaultMaxFontSize;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Dimension.defaultMaxValue = global::FlexGrid101.Android.Resource.Dimension.defaultMaxValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Dimension.defaultMinFontSize = global::FlexGrid101.Android.Resource.Dimension.defaultMinFontSize;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Dimension.defaultMinValue = global::FlexGrid101.Android.Resource.Dimension.defaultMinValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Dimension.defaultOrigin = global::FlexGrid101.Android.Resource.Dimension.defaultOrigin;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Dimension.defaultPointerWidth = global::FlexGrid101.Android.Resource.Dimension.defaultPointerWidth;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Dimension.defaultRadialStartAngle = global::FlexGrid101.Android.Resource.Dimension.defaultRadialStartAngle;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Dimension.defaultRadialSweepAngle = global::FlexGrid101.Android.Resource.Dimension.defaultRadialSweepAngle;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Dimension.defaultStepValue = global::FlexGrid101.Android.Resource.Dimension.defaultStepValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Dimension.defaultTargetValue = global::FlexGrid101.Android.Resource.Dimension.defaultTargetValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Dimension.defaultValue = global::FlexGrid101.Android.Resource.Dimension.defaultValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Dimension.defaultValueFontSize = global::FlexGrid101.Android.Resource.Dimension.defaultValueFontSize;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Drawable.ic_launcher = global::FlexGrid101.Android.Resource.Drawable.ic_launcher;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Id.ALL = global::FlexGrid101.Android.Resource.Id.ALL;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Id.DOWN = global::FlexGrid101.Android.Resource.Id.DOWN;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Id.LEFT = global::FlexGrid101.Android.Resource.Id.LEFT;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Id.MINMAX = global::FlexGrid101.Android.Resource.Id.MINMAX;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Id.NONE = global::FlexGrid101.Android.Resource.Id.NONE;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Id.RIGHT = global::FlexGrid101.Android.Resource.Id.RIGHT;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Id.UP = global::FlexGrid101.Android.Resource.Id.UP;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Id.VALUE = global::FlexGrid101.Android.Resource.Id.VALUE;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Integer.defaultFaceBorderColor = global::FlexGrid101.Android.Resource.Integer.defaultFaceBorderColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Integer.defaultFaceBorderWidth = global::FlexGrid101.Android.Resource.Integer.defaultFaceBorderWidth;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.String.ApplicationName = global::FlexGrid101.Android.Resource.String.ApplicationName;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.String.Hello = global::FlexGrid101.Android.Resource.String.Hello;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.String.app_name = global::FlexGrid101.Android.Resource.String.app_name;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.String.defaultFormat = global::FlexGrid101.Android.Resource.String.defaultFormat;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.String.defaultLinearGaugeDirection = global::FlexGrid101.Android.Resource.String.defaultLinearGaugeDirection;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.String.defaultMaxFontTypeface = global::FlexGrid101.Android.Resource.String.defaultMaxFontTypeface;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.String.defaultMinFontTypeface = global::FlexGrid101.Android.Resource.String.defaultMinFontTypeface;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.String.defaultValueFontTypeface = global::FlexGrid101.Android.Resource.String.defaultValueFontTypeface;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Style.AppBaseTheme = global::FlexGrid101.Android.Resource.Style.AppBaseTheme;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Style.AppTheme = global::FlexGrid101.Android.Resource.Style.AppTheme;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniBulletGraph = global::FlexGrid101.Android.Resource.Styleable.XuniBulletGraph;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniBulletGraph_gauge_bulletBadRangeColor = global::FlexGrid101.Android.Resource.Styleable.XuniBulletGraph_gauge_bulletBadRangeColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniBulletGraph_gauge_bulletBadValue = global::FlexGrid101.Android.Resource.Styleable.XuniBulletGraph_gauge_bulletBadValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniBulletGraph_gauge_bulletGoodRangeColor = global::FlexGrid101.Android.Resource.Styleable.XuniBulletGraph_gauge_bulletGoodRangeColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniBulletGraph_gauge_bulletGoodValue = global::FlexGrid101.Android.Resource.Styleable.XuniBulletGraph_gauge_bulletGoodValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniBulletGraph_gauge_bulletTargetRangeColor = global::FlexGrid101.Android.Resource.Styleable.XuniBulletGraph_gauge_bulletTargetRangeColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniBulletGraph_gauge_bulletTargetValue = global::FlexGrid101.Android.Resource.Styleable.XuniBulletGraph_gauge_bulletTargetValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge = global::FlexGrid101.Android.Resource.Styleable.XuniGauge;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_animated = global::FlexGrid101.Android.Resource.Styleable.XuniGauge_gauge_animated;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_backgroundColor = global::FlexGrid101.Android.Resource.Styleable.XuniGauge_gauge_backgroundColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_faceBorderColor = global::FlexGrid101.Android.Resource.Styleable.XuniGauge_gauge_faceBorderColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_faceBorderWidth = global::FlexGrid101.Android.Resource.Styleable.XuniGauge_gauge_faceBorderWidth;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_faceColor = global::FlexGrid101.Android.Resource.Styleable.XuniGauge_gauge_faceColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_format = global::FlexGrid101.Android.Resource.Styleable.XuniGauge_gauge_format;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_gaugeWidth = global::FlexGrid101.Android.Resource.Styleable.XuniGauge_gauge_gaugeWidth;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_maxFontColor = global::FlexGrid101.Android.Resource.Styleable.XuniGauge_gauge_maxFontColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_maxFontSize = global::FlexGrid101.Android.Resource.Styleable.XuniGauge_gauge_maxFontSize;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_maxFontTypeFace = global::FlexGrid101.Android.Resource.Styleable.XuniGauge_gauge_maxFontTypeFace;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_maxValue = global::FlexGrid101.Android.Resource.Styleable.XuniGauge_gauge_maxValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_minFontColor = global::FlexGrid101.Android.Resource.Styleable.XuniGauge_gauge_minFontColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_minFontSize = global::FlexGrid101.Android.Resource.Styleable.XuniGauge_gauge_minFontSize;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_minFontTypeFace = global::FlexGrid101.Android.Resource.Styleable.XuniGauge_gauge_minFontTypeFace;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_minValue = global::FlexGrid101.Android.Resource.Styleable.XuniGauge_gauge_minValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_origin = global::FlexGrid101.Android.Resource.Styleable.XuniGauge_gauge_origin;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_pointerColor = global::FlexGrid101.Android.Resource.Styleable.XuniGauge_gauge_pointerColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_pointerWidth = global::FlexGrid101.Android.Resource.Styleable.XuniGauge_gauge_pointerWidth;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_showRanges = global::FlexGrid101.Android.Resource.Styleable.XuniGauge_gauge_showRanges;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_showTextType = global::FlexGrid101.Android.Resource.Styleable.XuniGauge_gauge_showTextType;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_stepValue = global::FlexGrid101.Android.Resource.Styleable.XuniGauge_gauge_stepValue;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_value = global::FlexGrid101.Android.Resource.Styleable.XuniGauge_gauge_value;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_valueFontColor = global::FlexGrid101.Android.Resource.Styleable.XuniGauge_gauge_valueFontColor;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_valueFontSize = global::FlexGrid101.Android.Resource.Styleable.XuniGauge_gauge_valueFontSize;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniGauge_gauge_valueFontTypeFace = global::FlexGrid101.Android.Resource.Styleable.XuniGauge_gauge_valueFontTypeFace;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniLinearGauge = global::FlexGrid101.Android.Resource.Styleable.XuniLinearGauge;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniLinearGauge_gauge_linearGaugeDirection = global::FlexGrid101.Android.Resource.Styleable.XuniLinearGauge_gauge_linearGaugeDirection;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniRadialGauge = global::FlexGrid101.Android.Resource.Styleable.XuniRadialGauge;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniRadialGauge_gauge_radialStartAngle = global::FlexGrid101.Android.Resource.Styleable.XuniRadialGauge_gauge_radialStartAngle;
			global::Xuni.Forms.Gauge.Platform.Android.Resource.Styleable.XuniRadialGauge_gauge_radialSweepAngle = global::FlexGrid101.Android.Resource.Styleable.XuniRadialGauge_gauge_radialSweepAngle;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010048
			public const int allowSorting = 2130772040;
			
			// aapt resource value: 0x7f01003b
			public const int alternatingRowBackgroundColor = 2130772027;
			
			// aapt resource value: 0x7f010049
			public const int autoGenerateColumns = 2130772041;
			
			// aapt resource value: 0x7f010040
			public const int borderColor = 2130772032;
			
			// aapt resource value: 0x7f010041
			public const int borderWidth = 2130772033;
			
			// aapt resource value: 0x7f010036
			public const int cellBackgroundColor = 2130772022;
			
			// aapt resource value: 0x7f010033
			public const int cellPaddingBottom = 2130772019;
			
			// aapt resource value: 0x7f010030
			public const int cellPaddingLeft = 2130772016;
			
			// aapt resource value: 0x7f010032
			public const int cellPaddingRight = 2130772018;
			
			// aapt resource value: 0x7f010031
			public const int cellPaddingTop = 2130772017;
			
			// aapt resource value: 0x7f01002c
			public const int columnHeaderBackgroundColor = 2130772012;
			
			// aapt resource value: 0x7f01002d
			public const int columnHeaderFontColor = 2130772013;
			
			// aapt resource value: 0x7f010028
			public const int columnHeaderFontSize = 2130772008;
			
			// aapt resource value: 0x7f010029
			public const int columnHeaderFontTypeface = 2130772009;
			
			// aapt resource value: 0x7f010022
			public const int columnHeaderFontWeight = 2130772002;
			
			// aapt resource value: 0x7f010037
			public const int fontColor = 2130772023;
			
			// aapt resource value: 0x7f010034
			public const int fontSize = 2130772020;
			
			// aapt resource value: 0x7f010035
			public const int fontTypeface = 2130772021;
			
			// aapt resource value: 0x7f010024
			public const int fontWeight = 2130772004;
			
			// aapt resource value: 0x7f010018
			public const int gauge_animated = 2130771992;
			
			// aapt resource value: 0x7f010002
			public const int gauge_backgroundColor = 2130771970;
			
			// aapt resource value: 0x7f01001d
			public const int gauge_bulletBadRangeColor = 2130771997;
			
			// aapt resource value: 0x7f01001f
			public const int gauge_bulletBadValue = 2130771999;
			
			// aapt resource value: 0x7f01001c
			public const int gauge_bulletGoodRangeColor = 2130771996;
			
			// aapt resource value: 0x7f010020
			public const int gauge_bulletGoodValue = 2130772000;
			
			// aapt resource value: 0x7f01001e
			public const int gauge_bulletTargetRangeColor = 2130771998;
			
			// aapt resource value: 0x7f010021
			public const int gauge_bulletTargetValue = 2130772001;
			
			// aapt resource value: 0x7f010010
			public const int gauge_faceBorderColor = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int gauge_faceBorderWidth = 2130771985;
			
			// aapt resource value: 0x7f01000e
			public const int gauge_faceColor = 2130771982;
			
			// aapt resource value: 0x7f010013
			public const int gauge_format = 2130771987;
			
			// aapt resource value: 0x7f01000c
			public const int gauge_gaugeWidth = 2130771980;
			
			// aapt resource value: 0x7f010000
			public const int gauge_linearGaugeDirection = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int gauge_maxFontColor = 2130771973;
			
			// aapt resource value: 0x7f010008
			public const int gauge_maxFontSize = 2130771976;
			
			// aapt resource value: 0x7f01000b
			public const int gauge_maxFontTypeFace = 2130771979;
			
			// aapt resource value: 0x7f010015
			public const int gauge_maxValue = 2130771989;
			
			// aapt resource value: 0x7f010004
			public const int gauge_minFontColor = 2130771972;
			
			// aapt resource value: 0x7f010007
			public const int gauge_minFontSize = 2130771975;
			
			// aapt resource value: 0x7f01000a
			public const int gauge_minFontTypeFace = 2130771978;
			
			// aapt resource value: 0x7f010016
			public const int gauge_minValue = 2130771990;
			
			// aapt resource value: 0x7f010012
			public const int gauge_origin = 2130771986;
			
			// aapt resource value: 0x7f01000f
			public const int gauge_pointerColor = 2130771983;
			
			// aapt resource value: 0x7f01000d
			public const int gauge_pointerWidth = 2130771981;
			
			// aapt resource value: 0x7f01001a
			public const int gauge_radialStartAngle = 2130771994;
			
			// aapt resource value: 0x7f01001b
			public const int gauge_radialSweepAngle = 2130771995;
			
			// aapt resource value: 0x7f010019
			public const int gauge_showRanges = 2130771993;
			
			// aapt resource value: 0x7f010001
			public const int gauge_showTextType = 2130771969;
			
			// aapt resource value: 0x7f010017
			public const int gauge_stepValue = 2130771991;
			
			// aapt resource value: 0x7f010014
			public const int gauge_value = 2130771988;
			
			// aapt resource value: 0x7f010003
			public const int gauge_valueFontColor = 2130771971;
			
			// aapt resource value: 0x7f010006
			public const int gauge_valueFontSize = 2130771974;
			
			// aapt resource value: 0x7f010009
			public const int gauge_valueFontTypeFace = 2130771977;
			
			// aapt resource value: 0x7f010039
			public const int gridLinesColor = 2130772025;
			
			// aapt resource value: 0x7f010025
			public const int gridLinesVisibility = 2130772005;
			
			// aapt resource value: 0x7f01003a
			public const int gridLinesWidth = 2130772026;
			
			// aapt resource value: 0x7f010044
			public const int groupHeaderFormat = 2130772036;
			
			// aapt resource value: 0x7f010042
			public const int groupRowBackgroundColor = 2130772034;
			
			// aapt resource value: 0x7f010043
			public const int groupRowFontColor = 2130772035;
			
			// aapt resource value: 0x7f010038
			public const int headerGridLinesColor = 2130772024;
			
			// aapt resource value: 0x7f010027
			public const int headersVisibility = 2130772007;
			
			// aapt resource value: 0x7f010046
			public const int readOnly = 2130772038;
			
			// aapt resource value: 0x7f01002e
			public const int rowHeaderBackgroundColor = 2130772014;
			
			// aapt resource value: 0x7f01002f
			public const int rowHeaderFontColor = 2130772015;
			
			// aapt resource value: 0x7f01002a
			public const int rowHeaderFontSize = 2130772010;
			
			// aapt resource value: 0x7f01002b
			public const int rowHeaderFontTypeface = 2130772011;
			
			// aapt resource value: 0x7f010023
			public const int rowHeaderFontWeight = 2130772003;
			
			// aapt resource value: 0x7f01003e
			public const int selectionAdornerBorderColor = 2130772030;
			
			// aapt resource value: 0x7f01003d
			public const int selectionAdornerColor = 2130772029;
			
			// aapt resource value: 0x7f01003c
			public const int selectionBackgroundColor = 2130772028;
			
			// aapt resource value: 0x7f01003f
			public const int selectionFontColor = 2130772031;
			
			// aapt resource value: 0x7f010026
			public const int selectionMode = 2130772006;
			
			// aapt resource value: 0x7f010047
			public const int showGroups = 2130772039;
			
			// aapt resource value: 0x7f010045
			public const int showSort = 2130772037;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f0a0000
			public const int defaultAnimated = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int defaultShowRanges = 2131361793;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080004
			public const int defaultBulletBadRangeColor = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int defaultBulletGoodRangeColor = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int defaultBulletGraphPointerColor = 2131230722;
			
			// aapt resource value: 0x7f080005
			public const int defaultBulletTargetRangeColor = 2131230725;
			
			// aapt resource value: 0x7f080000
			public const int defaultFaceColor = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int defaultPointerColor = 2131230721;
			
			// aapt resource value: 0x7f080006
			public const int filter_view_background = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int filter_view_text = 2131230727;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070010
			public const int activity_horizontal_margin = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int activity_vertical_margin = 2131165201;
			
			// aapt resource value: 0x7f07000d
			public const int defaultBadValue = 2131165197;
			
			// aapt resource value: 0x7f070005
			public const int defaultBulletGraphPointerWidth = 2131165189;
			
			// aapt resource value: 0x7f070016
			public const int defaultCellPaddingBottom = 2131165206;
			
			// aapt resource value: 0x7f070013
			public const int defaultCellPaddingLeft = 2131165203;
			
			// aapt resource value: 0x7f070015
			public const int defaultCellPaddingRight = 2131165205;
			
			// aapt resource value: 0x7f070014
			public const int defaultCellPaddingTop = 2131165204;
			
			// aapt resource value: 0x7f070012
			public const int defaultFontSize = 2131165202;
			
			// aapt resource value: 0x7f070003
			public const int defaultGaugeWidth = 2131165187;
			
			// aapt resource value: 0x7f07000e
			public const int defaultGoodValue = 2131165198;
			
			// aapt resource value: 0x7f070002
			public const int defaultMaxFontSize = 2131165186;
			
			// aapt resource value: 0x7f07000a
			public const int defaultMaxValue = 2131165194;
			
			// aapt resource value: 0x7f070001
			public const int defaultMinFontSize = 2131165185;
			
			// aapt resource value: 0x7f07000b
			public const int defaultMinValue = 2131165195;
			
			// aapt resource value: 0x7f070008
			public const int defaultOrigin = 2131165192;
			
			// aapt resource value: 0x7f070004
			public const int defaultPointerWidth = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int defaultRadialStartAngle = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int defaultRadialSweepAngle = 2131165191;
			
			// aapt resource value: 0x7f07000c
			public const int defaultStepValue = 2131165196;
			
			// aapt resource value: 0x7f07000f
			public const int defaultTargetValue = 2131165199;
			
			// aapt resource value: 0x7f070009
			public const int defaultValue = 2131165193;
			
			// aapt resource value: 0x7f070000
			public const int defaultValueFontSize = 2131165184;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_arrow_collapse_white_48dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_edit = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_filter = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_filter_remove = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_launcher = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_sort_ascending = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_sort_descending = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050007
			public const int ALL = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int BOLD = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int BOLD_ITALIC = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int CELL = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int CELL_RANGE = 2131034127;
			
			// aapt resource value: 0x7f05000c
			public const int COLUMN = 2131034124;
			
			// aapt resource value: 0x7f050003
			public const int DOWN = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int ITALIC = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int LEFT = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int MINMAX = 2131034118;
			
			// aapt resource value: 0x7f050011
			public const int MyButton = 2131034129;
			
			// aapt resource value: 0x7f050004
			public const int NONE = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int NORMAL = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int RIGHT = 2131034113;
			
			// aapt resource value: 0x7f05000d
			public const int ROW = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int ROW_RANGE = 2131034128;
			
			// aapt resource value: 0x7f050002
			public const int UP = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int VALUE = 2131034117;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f090003
			public const int defaultCellFontGravity = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int defaultCellFontWeight = 2131296258;
			
			// aapt resource value: 0x7f090000
			public const int defaultFaceBorderColor = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int defaultFaceBorderWidth = 2131296257;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f04000e
			public const int defaultCellFontTypeface = 2130968590;
			
			// aapt resource value: 0x7f040007
			public const int defaultFormat = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int defaultLinearGaugeDirection = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int defaultMaxFontTypeface = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int defaultMinFontTypeface = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int defaultValueFontTypeface = 2130968579;
			
			// aapt resource value: 0x7f040008
			public const int filter_view_ascending = 2130968584;
			
			// aapt resource value: 0x7f04000a
			public const int filter_view_clear = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int filter_view_descending = 2130968585;
			
			// aapt resource value: 0x7f04000b
			public const int filter_view_done = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int filter_view_select_all = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int groupHeaderFormat = 2130968589;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppBaseTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int AppTheme = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FlexGrid = new int[]
			{
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016,
					2130772017,
					2130772018,
					2130772019,
					2130772020,
					2130772021,
					2130772022,
					2130772023,
					2130772024,
					2130772025,
					2130772026,
					2130772027,
					2130772028,
					2130772029,
					2130772030,
					2130772031,
					2130772032,
					2130772033,
					2130772034,
					2130772035,
					2130772036,
					2130772037,
					2130772038,
					2130772039,
					2130772040,
					2130772041};
			
			// aapt resource value: 38
			public const int FlexGrid_allowSorting = 38;
			
			// aapt resource value: 25
			public const int FlexGrid_alternatingRowBackgroundColor = 25;
			
			// aapt resource value: 39
			public const int FlexGrid_autoGenerateColumns = 39;
			
			// aapt resource value: 30
			public const int FlexGrid_borderColor = 30;
			
			// aapt resource value: 31
			public const int FlexGrid_borderWidth = 31;
			
			// aapt resource value: 20
			public const int FlexGrid_cellBackgroundColor = 20;
			
			// aapt resource value: 17
			public const int FlexGrid_cellPaddingBottom = 17;
			
			// aapt resource value: 14
			public const int FlexGrid_cellPaddingLeft = 14;
			
			// aapt resource value: 16
			public const int FlexGrid_cellPaddingRight = 16;
			
			// aapt resource value: 15
			public const int FlexGrid_cellPaddingTop = 15;
			
			// aapt resource value: 10
			public const int FlexGrid_columnHeaderBackgroundColor = 10;
			
			// aapt resource value: 11
			public const int FlexGrid_columnHeaderFontColor = 11;
			
			// aapt resource value: 6
			public const int FlexGrid_columnHeaderFontSize = 6;
			
			// aapt resource value: 7
			public const int FlexGrid_columnHeaderFontTypeface = 7;
			
			// aapt resource value: 0
			public const int FlexGrid_columnHeaderFontWeight = 0;
			
			// aapt resource value: 21
			public const int FlexGrid_fontColor = 21;
			
			// aapt resource value: 18
			public const int FlexGrid_fontSize = 18;
			
			// aapt resource value: 19
			public const int FlexGrid_fontTypeface = 19;
			
			// aapt resource value: 2
			public const int FlexGrid_fontWeight = 2;
			
			// aapt resource value: 23
			public const int FlexGrid_gridLinesColor = 23;
			
			// aapt resource value: 3
			public const int FlexGrid_gridLinesVisibility = 3;
			
			// aapt resource value: 24
			public const int FlexGrid_gridLinesWidth = 24;
			
			// aapt resource value: 34
			public const int FlexGrid_groupHeaderFormat = 34;
			
			// aapt resource value: 32
			public const int FlexGrid_groupRowBackgroundColor = 32;
			
			// aapt resource value: 33
			public const int FlexGrid_groupRowFontColor = 33;
			
			// aapt resource value: 22
			public const int FlexGrid_headerGridLinesColor = 22;
			
			// aapt resource value: 5
			public const int FlexGrid_headersVisibility = 5;
			
			// aapt resource value: 36
			public const int FlexGrid_readOnly = 36;
			
			// aapt resource value: 12
			public const int FlexGrid_rowHeaderBackgroundColor = 12;
			
			// aapt resource value: 13
			public const int FlexGrid_rowHeaderFontColor = 13;
			
			// aapt resource value: 8
			public const int FlexGrid_rowHeaderFontSize = 8;
			
			// aapt resource value: 9
			public const int FlexGrid_rowHeaderFontTypeface = 9;
			
			// aapt resource value: 1
			public const int FlexGrid_rowHeaderFontWeight = 1;
			
			// aapt resource value: 28
			public const int FlexGrid_selectionAdornerBorderColor = 28;
			
			// aapt resource value: 27
			public const int FlexGrid_selectionAdornerColor = 27;
			
			// aapt resource value: 26
			public const int FlexGrid_selectionBackgroundColor = 26;
			
			// aapt resource value: 29
			public const int FlexGrid_selectionFontColor = 29;
			
			// aapt resource value: 4
			public const int FlexGrid_selectionMode = 4;
			
			// aapt resource value: 37
			public const int FlexGrid_showGroups = 37;
			
			// aapt resource value: 35
			public const int FlexGrid_showSort = 35;
			
			public static int[] XuniBulletGraph = new int[]
			{
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001};
			
			// aapt resource value: 1
			public const int XuniBulletGraph_gauge_bulletBadRangeColor = 1;
			
			// aapt resource value: 3
			public const int XuniBulletGraph_gauge_bulletBadValue = 3;
			
			// aapt resource value: 0
			public const int XuniBulletGraph_gauge_bulletGoodRangeColor = 0;
			
			// aapt resource value: 4
			public const int XuniBulletGraph_gauge_bulletGoodValue = 4;
			
			// aapt resource value: 2
			public const int XuniBulletGraph_gauge_bulletTargetRangeColor = 2;
			
			// aapt resource value: 5
			public const int XuniBulletGraph_gauge_bulletTargetValue = 5;
			
			public static int[] XuniGauge = new int[]
			{
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 23
			public const int XuniGauge_gauge_animated = 23;
			
			// aapt resource value: 1
			public const int XuniGauge_gauge_backgroundColor = 1;
			
			// aapt resource value: 15
			public const int XuniGauge_gauge_faceBorderColor = 15;
			
			// aapt resource value: 16
			public const int XuniGauge_gauge_faceBorderWidth = 16;
			
			// aapt resource value: 13
			public const int XuniGauge_gauge_faceColor = 13;
			
			// aapt resource value: 18
			public const int XuniGauge_gauge_format = 18;
			
			// aapt resource value: 11
			public const int XuniGauge_gauge_gaugeWidth = 11;
			
			// aapt resource value: 4
			public const int XuniGauge_gauge_maxFontColor = 4;
			
			// aapt resource value: 7
			public const int XuniGauge_gauge_maxFontSize = 7;
			
			// aapt resource value: 10
			public const int XuniGauge_gauge_maxFontTypeFace = 10;
			
			// aapt resource value: 20
			public const int XuniGauge_gauge_maxValue = 20;
			
			// aapt resource value: 3
			public const int XuniGauge_gauge_minFontColor = 3;
			
			// aapt resource value: 6
			public const int XuniGauge_gauge_minFontSize = 6;
			
			// aapt resource value: 9
			public const int XuniGauge_gauge_minFontTypeFace = 9;
			
			// aapt resource value: 21
			public const int XuniGauge_gauge_minValue = 21;
			
			// aapt resource value: 17
			public const int XuniGauge_gauge_origin = 17;
			
			// aapt resource value: 14
			public const int XuniGauge_gauge_pointerColor = 14;
			
			// aapt resource value: 12
			public const int XuniGauge_gauge_pointerWidth = 12;
			
			// aapt resource value: 24
			public const int XuniGauge_gauge_showRanges = 24;
			
			// aapt resource value: 0
			public const int XuniGauge_gauge_showTextType = 0;
			
			// aapt resource value: 22
			public const int XuniGauge_gauge_stepValue = 22;
			
			// aapt resource value: 19
			public const int XuniGauge_gauge_value = 19;
			
			// aapt resource value: 2
			public const int XuniGauge_gauge_valueFontColor = 2;
			
			// aapt resource value: 5
			public const int XuniGauge_gauge_valueFontSize = 5;
			
			// aapt resource value: 8
			public const int XuniGauge_gauge_valueFontTypeFace = 8;
			
			public static int[] XuniLinearGauge = new int[]
			{
					2130771968};
			
			// aapt resource value: 0
			public const int XuniLinearGauge_gauge_linearGaugeDirection = 0;
			
			public static int[] XuniRadialGauge = new int[]
			{
					2130771994,
					2130771995};
			
			// aapt resource value: 0
			public const int XuniRadialGauge_gauge_radialStartAngle = 0;
			
			// aapt resource value: 1
			public const int XuniRadialGauge_gauge_radialSweepAngle = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
