//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexPieDemo.Data.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_jp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_jp() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlexPieDemo.Data.Resources.AppResources.jp", typeof(AppResources_jp).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ロードおよび更新アニメーションモードを示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AnimationDescription {
            get {
                return ResourceManager.GetString("AnimationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アニメーション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AnimationTitle {
            get {
                return ResourceManager.GetString("AnimationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   内側半径、オフセット、開始角度を示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BasicFeaturesDescription {
            get {
                return ResourceManager.GetString("BasicFeaturesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   基本機能 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BasicFeaturesTitle {
            get {
                return ResourceManager.GetString("BasicFeaturesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カスタマイズされたツールチップを表示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CustomTooltipsDescription {
            get {
                return ResourceManager.GetString("CustomTooltipsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カスタムツールチップ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CustomTooltipsTitle {
            get {
                return ResourceManager.GetString("CustomTooltipsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   静的なデータラベルを表示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DataLabelsDescription {
            get {
                return ResourceManager.GetString("DataLabelsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データラベル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DataLabelsTitle {
            get {
                return ResourceManager.GetString("DataLabelsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FlexPie の画像をエクスポートする方法を示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExportImageDescription {
            get {
                return ResourceManager.GetString("ExportImageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像のエクスポート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExportImageTitle {
            get {
                return ResourceManager.GetString("ExportImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ツールチップを備えたシンプルな円グラフを示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GettingStartedDescription {
            get {
                return ResourceManager.GetString("GettingStartedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   はじめに に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GettingStartedTitle {
            get {
                return ResourceManager.GetString("GettingStartedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   基本的なヘッダ、フッタ、凡例の配置を示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LegendSampleDescription {
            get {
                return ResourceManager.GetString("LegendSampleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   凡例とタイトル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LegendSampleTitle {
            get {
                return ResourceManager.GetString("LegendSampleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択アニメーション、オフセット、位置を示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectionDescription {
            get {
                return ResourceManager.GetString("SelectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectionTitle {
            get {
                return ResourceManager.GetString("SelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用可能なパレットを示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ThemingDescription {
            get {
                return ResourceManager.GetString("ThemingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テーマ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ThemingTitle {
            get {
                return ResourceManager.GetString("ThemingTitle", resourceCulture);
            }
        }
    }
}
