//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollectionView101.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_jp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_jp() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CollectionView101.Resources.AppResources.jp", typeof(AppResources_jp).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   項目を入力して項目のリストをフィルタリングします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilteringDescription {
            get {
                return ResourceManager.GetString("FilteringDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フィルタリング に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilteringTitle {
            get {
                return ResourceManager.GetString("FilteringTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フィルタリングするテキストを入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterPlaceholderText {
            get {
                return ResourceManager.GetString("FilterPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YouTube ビデオのグループ化されたリストを表示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GroupingDescription {
            get {
                return ResourceManager.GetString("GroupingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループ化 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GroupingTitle {
            get {
                return ResourceManager.GetString("GroupingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インターネットからデータを取得するときに問題が発生しました。\nインターネット接続をチェックしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InternetConnectionError {
            get {
                return ResourceManager.GetString("InternetConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   下にスクロールしたときにオンデマンドで ListView の項目をロードします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OnDemandDescription {
            get {
                return ResourceManager.GetString("OnDemandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オンデマンド に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OnDemandTitle {
            get {
                return ResourceManager.GetString("OnDemandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アクションバーから項目のリストをソートします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SortingDescription {
            get {
                return ResourceManager.GetString("SortingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ソート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SortingTitle {
            get {
                return ResourceManager.GetString("SortingTitle", resourceCulture);
            }
        }
    }
}
