#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("FlexPieDemo.Droid.Resource", IsApplication=true)]

namespace FlexPieDemo.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::FlexPieDemo.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::FlexPieDemo.Droid.Resource.String.Hello;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Array.flexPieCerulanPalette = global::FlexPieDemo.Droid.Resource.Array.flexPieCerulanPalette;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Array.flexPieCocoaPalette = global::FlexPieDemo.Droid.Resource.Array.flexPieCocoaPalette;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Array.flexPieCoralPalette = global::FlexPieDemo.Droid.Resource.Array.flexPieCoralPalette;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Array.flexPieCyborgPalette = global::FlexPieDemo.Droid.Resource.Array.flexPieCyborgPalette;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Array.flexPieDarkPalette = global::FlexPieDemo.Droid.Resource.Array.flexPieDarkPalette;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Array.flexPieDarklyPalette = global::FlexPieDemo.Droid.Resource.Array.flexPieDarklyPalette;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Array.flexPieDefaultflexPiePalette = global::FlexPieDemo.Droid.Resource.Array.flexPieDefaultflexPiePalette;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Array.flexPieFlatlyPalette = global::FlexPieDemo.Droid.Resource.Array.flexPieFlatlyPalette;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Array.flexPieHighConstrastPalette = global::FlexPieDemo.Droid.Resource.Array.flexPieHighConstrastPalette;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Array.flexPieLightPalette = global::FlexPieDemo.Droid.Resource.Array.flexPieLightPalette;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Array.flexPieMaterialPalette = global::FlexPieDemo.Droid.Resource.Array.flexPieMaterialPalette;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Array.flexPieMidnightPalette = global::FlexPieDemo.Droid.Resource.Array.flexPieMidnightPalette;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Array.flexPieMinimalPalette = global::FlexPieDemo.Droid.Resource.Array.flexPieMinimalPalette;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Array.flexPieModernPalette = global::FlexPieDemo.Droid.Resource.Array.flexPieModernPalette;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Array.flexPieOrganicPalette = global::FlexPieDemo.Droid.Resource.Array.flexPieOrganicPalette;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Array.flexPieSlatePalette = global::FlexPieDemo.Droid.Resource.Array.flexPieSlatePalette;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Array.flexPieSuperheroPalette = global::FlexPieDemo.Droid.Resource.Array.flexPieSuperheroPalette;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_animated = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_animated;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_backgroundColor = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_backgroundColor;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_binding = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_binding;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_bindingName = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_bindingName;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_borderColor = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_borderColor;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_borderWidth = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_borderWidth;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_datalabel_FontColor = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_datalabel_FontColor;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_datalabel_FontSize = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_datalabel_FontSize;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_datalabel_FontTypeface = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_datalabel_FontTypeface;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_datalabel_FontWeight = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_datalabel_FontWeight;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_datalabel_backgroundColor = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_datalabel_backgroundColor;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_datalabel_borderColor = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_datalabel_borderColor;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_datalabel_borderWidth = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_datalabel_borderWidth;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_datalabel_position = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_datalabel_position;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_footer = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_footer;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_footerFontColor = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_footerFontColor;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_footerFontGravity = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_footerFontGravity;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_footerFontSize = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_footerFontSize;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_footerFontTypeface = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_footerFontTypeface;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_footerFontWeight = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_footerFontWeight;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_header = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_header;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_headerFontColor = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_headerFontColor;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_headerFontGravity = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_headerFontGravity;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_headerFontSize = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_headerFontSize;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_headerFontTypeface = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_headerFontTypeface;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_headerFontWeight = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_headerFontWeight;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_innerRadius = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_innerRadius;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_legend_FontColor = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_legend_FontColor;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_legend_FontSize = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_legend_FontSize;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_legend_FontTypeface = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_legend_FontTypeface;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_legend_FontWeight = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_legend_FontWeight;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_legend_backgroundColor = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_legend_backgroundColor;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_legend_borderColor = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_legend_borderColor;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_legend_borderWidth = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_legend_borderWidth;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_legend_orientation = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_legend_orientation;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_legend_position = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_legend_position;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_loadAnimation_duration = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_loadAnimation_duration;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_loadAnimation_loadAnimationMode = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_loadAnimation_loadAnimationMode;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_loadAnimation_startDelay = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_loadAnimation_startDelay;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_offset = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_offset;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_palette = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_palette;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_plotAreabackgroundColor = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_plotAreabackgroundColor;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_reversed = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_reversed;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_selectAnimation_duration = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_selectAnimation_duration;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_selectAnimation_startDelay = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_selectAnimation_startDelay;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_selectedBorderColor = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_selectedBorderColor;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_selectedBorderWidth = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_selectedBorderWidth;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_selectedItemOffset = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_selectedItemOffset;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_selectedItemPosition = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_selectedItemPosition;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_selectionMode = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_selectionMode;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_sliceBorderWidth = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_sliceBorderWidth;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_startAngle = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_startAngle;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_updateAnimation_duration = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_updateAnimation_duration;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Attribute.flexPie_updateAnimation_startDelay = global::FlexPieDemo.Droid.Resource.Attribute.flexPie_updateAnimation_startDelay;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Boolean.defaultFlexPieAnimated = global::FlexPieDemo.Droid.Resource.Boolean.defaultFlexPieAnimated;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Boolean.defaultFlexPieReversed = global::FlexPieDemo.Droid.Resource.Boolean.defaultFlexPieReversed;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Dimension.defaultFlexPieBorderWidth = global::FlexPieDemo.Droid.Resource.Dimension.defaultFlexPieBorderWidth;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Dimension.defaultFlexPieDatalabel_FontSize = global::FlexPieDemo.Droid.Resource.Dimension.defaultFlexPieDatalabel_FontSize;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Dimension.defaultFlexPieDatalabel_borderWidth = global::FlexPieDemo.Droid.Resource.Dimension.defaultFlexPieDatalabel_borderWidth;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Dimension.defaultFlexPieFooterFontSize = global::FlexPieDemo.Droid.Resource.Dimension.defaultFlexPieFooterFontSize;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Dimension.defaultFlexPieHeaderFontSize = global::FlexPieDemo.Droid.Resource.Dimension.defaultFlexPieHeaderFontSize;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Dimension.defaultFlexPieInnerRadius = global::FlexPieDemo.Droid.Resource.Dimension.defaultFlexPieInnerRadius;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Dimension.defaultFlexPieLegend_FontSize = global::FlexPieDemo.Droid.Resource.Dimension.defaultFlexPieLegend_FontSize;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Dimension.defaultFlexPieLegend_borderWidth = global::FlexPieDemo.Droid.Resource.Dimension.defaultFlexPieLegend_borderWidth;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Dimension.defaultFlexPieOffset = global::FlexPieDemo.Droid.Resource.Dimension.defaultFlexPieOffset;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Dimension.defaultFlexPieSelectedBorderWidth = global::FlexPieDemo.Droid.Resource.Dimension.defaultFlexPieSelectedBorderWidth;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Dimension.defaultFlexPieSelectedItemOffset = global::FlexPieDemo.Droid.Resource.Dimension.defaultFlexPieSelectedItemOffset;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Dimension.defaultFlexPieSliceBorderWidth = global::FlexPieDemo.Droid.Resource.Dimension.defaultFlexPieSliceBorderWidth;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Dimension.defaultFlexPieStartAngle = global::FlexPieDemo.Droid.Resource.Dimension.defaultFlexPieStartAngle;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Drawable.dct = global::FlexPieDemo.Droid.Resource.Drawable.dct;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Drawable.ic_launcher = global::FlexPieDemo.Droid.Resource.Drawable.ic_launcher;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Id.ALL = global::FlexPieDemo.Droid.Resource.Id.ALL;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Id.AUTO = global::FlexPieDemo.Droid.Resource.Id.AUTO;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Id.BOLD = global::FlexPieDemo.Droid.Resource.Id.BOLD;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Id.BOLD_ITALIC = global::FlexPieDemo.Droid.Resource.Id.BOLD_ITALIC;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Id.BOTTOM = global::FlexPieDemo.Droid.Resource.Id.BOTTOM;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Id.CENTER = global::FlexPieDemo.Droid.Resource.Id.CENTER;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Id.CENTER_HORIZONTAL = global::FlexPieDemo.Droid.Resource.Id.CENTER_HORIZONTAL;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Id.HORIZONTAL = global::FlexPieDemo.Droid.Resource.Id.HORIZONTAL;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Id.INSIDE = global::FlexPieDemo.Droid.Resource.Id.INSIDE;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Id.ITALIC = global::FlexPieDemo.Droid.Resource.Id.ITALIC;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Id.LEFT = global::FlexPieDemo.Droid.Resource.Id.LEFT;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Id.NONE = global::FlexPieDemo.Droid.Resource.Id.NONE;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Id.NORMAL = global::FlexPieDemo.Droid.Resource.Id.NORMAL;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Id.OUTSIDE = global::FlexPieDemo.Droid.Resource.Id.OUTSIDE;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Id.POINT = global::FlexPieDemo.Droid.Resource.Id.POINT;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Id.RIGHT = global::FlexPieDemo.Droid.Resource.Id.RIGHT;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Id.SERIES = global::FlexPieDemo.Droid.Resource.Id.SERIES;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Id.TOP = global::FlexPieDemo.Droid.Resource.Id.TOP;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Id.VERTICAL = global::FlexPieDemo.Droid.Resource.Id.VERTICAL;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Id.tooltipContent = global::FlexPieDemo.Droid.Resource.Id.tooltipContent;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Id.tooltipTitle = global::FlexPieDemo.Droid.Resource.Id.tooltipTitle;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Integer.defaultFlexPieDatalabelPosition = global::FlexPieDemo.Droid.Resource.Integer.defaultFlexPieDatalabelPosition;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Integer.defaultFlexPieDatalabel_FontWeight = global::FlexPieDemo.Droid.Resource.Integer.defaultFlexPieDatalabel_FontWeight;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Integer.defaultFlexPieFooterFontGravity = global::FlexPieDemo.Droid.Resource.Integer.defaultFlexPieFooterFontGravity;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Integer.defaultFlexPieFooterFontWeight = global::FlexPieDemo.Droid.Resource.Integer.defaultFlexPieFooterFontWeight;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Integer.defaultFlexPieHeaderFontGravity = global::FlexPieDemo.Droid.Resource.Integer.defaultFlexPieHeaderFontGravity;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Integer.defaultFlexPieHeaderFontWeight = global::FlexPieDemo.Droid.Resource.Integer.defaultFlexPieHeaderFontWeight;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Integer.defaultFlexPieLegendOrientation = global::FlexPieDemo.Droid.Resource.Integer.defaultFlexPieLegendOrientation;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Integer.defaultFlexPieLegendPosition = global::FlexPieDemo.Droid.Resource.Integer.defaultFlexPieLegendPosition;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Integer.defaultFlexPieLegend_FontWeight = global::FlexPieDemo.Droid.Resource.Integer.defaultFlexPieLegend_FontWeight;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Integer.defaultFlexPieLoadAnimationDuration = global::FlexPieDemo.Droid.Resource.Integer.defaultFlexPieLoadAnimationDuration;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Integer.defaultFlexPieLoadAnimationMode = global::FlexPieDemo.Droid.Resource.Integer.defaultFlexPieLoadAnimationMode;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Integer.defaultFlexPieLoadAnimationStartDelay = global::FlexPieDemo.Droid.Resource.Integer.defaultFlexPieLoadAnimationStartDelay;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Integer.defaultFlexPieSelectAnimationDuration = global::FlexPieDemo.Droid.Resource.Integer.defaultFlexPieSelectAnimationDuration;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Integer.defaultFlexPieSelectAnimationStartDelay = global::FlexPieDemo.Droid.Resource.Integer.defaultFlexPieSelectAnimationStartDelay;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Integer.defaultFlexPieSelectedItemPosition = global::FlexPieDemo.Droid.Resource.Integer.defaultFlexPieSelectedItemPosition;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Integer.defaultFlexPieSelectionMode = global::FlexPieDemo.Droid.Resource.Integer.defaultFlexPieSelectionMode;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Integer.defaultFlexPieUpdateAnimationDuration = global::FlexPieDemo.Droid.Resource.Integer.defaultFlexPieUpdateAnimationDuration;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Integer.defaultFlexPieUpdateAnimationStartDelay = global::FlexPieDemo.Droid.Resource.Integer.defaultFlexPieUpdateAnimationStartDelay;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Layout.tooltip = global::FlexPieDemo.Droid.Resource.Layout.tooltip;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.String.ApplicationName = global::FlexPieDemo.Droid.Resource.String.ApplicationName;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.String.Hello = global::FlexPieDemo.Droid.Resource.String.Hello;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.String.defaultFlexPieDatalabel_FontTypeface = global::FlexPieDemo.Droid.Resource.String.defaultFlexPieDatalabel_FontTypeface;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.String.defaultFlexPieFooterFontTypeface = global::FlexPieDemo.Droid.Resource.String.defaultFlexPieFooterFontTypeface;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.String.defaultFlexPieHeaderFontTypeface = global::FlexPieDemo.Droid.Resource.String.defaultFlexPieHeaderFontTypeface;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.String.defaultFlexPieLegend_FontTypeface = global::FlexPieDemo.Droid.Resource.String.defaultFlexPieLegend_FontTypeface;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Style.AppBaseTheme = global::FlexPieDemo.Droid.Resource.Style.AppBaseTheme;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Style.AppTheme = global::FlexPieDemo.Droid.Resource.Style.AppTheme;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_animated = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_animated;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_backgroundColor = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_backgroundColor;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_binding = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_binding;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_bindingName = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_bindingName;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_borderColor = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_borderColor;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_borderWidth = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_borderWidth;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_datalabel_FontColor = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_datalabel_FontColor;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_datalabel_FontSize = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_datalabel_FontSize;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_datalabel_FontTypeface = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_datalabel_FontTypeface;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_datalabel_FontWeight = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_datalabel_FontWeight;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_datalabel_backgroundColor = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_datalabel_backgroundColor;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_datalabel_borderColor = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_datalabel_borderColor;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_datalabel_borderWidth = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_datalabel_borderWidth;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_datalabel_position = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_datalabel_position;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_footer = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_footer;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_footerFontColor = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_footerFontColor;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_footerFontGravity = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_footerFontGravity;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_footerFontSize = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_footerFontSize;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_footerFontTypeface = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_footerFontTypeface;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_footerFontWeight = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_footerFontWeight;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_header = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_header;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_headerFontColor = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_headerFontColor;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_headerFontGravity = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_headerFontGravity;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_headerFontSize = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_headerFontSize;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_headerFontTypeface = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_headerFontTypeface;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_headerFontWeight = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_headerFontWeight;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_innerRadius = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_innerRadius;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_legend_FontColor = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_legend_FontColor;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_legend_FontSize = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_legend_FontSize;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_legend_FontTypeface = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_legend_FontTypeface;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_legend_FontWeight = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_legend_FontWeight;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_legend_backgroundColor = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_legend_backgroundColor;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_legend_borderColor = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_legend_borderColor;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_legend_borderWidth = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_legend_borderWidth;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_legend_orientation = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_legend_orientation;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_legend_position = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_legend_position;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_loadAnimation_duration = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_loadAnimation_duration;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_loadAnimation_loadAnimationMode = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_loadAnimation_loadAnimationMode;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_loadAnimation_startDelay = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_loadAnimation_startDelay;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_offset = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_offset;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_palette = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_palette;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_plotAreabackgroundColor = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_plotAreabackgroundColor;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_reversed = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_reversed;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_selectAnimation_duration = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_selectAnimation_duration;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_selectAnimation_startDelay = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_selectAnimation_startDelay;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_selectedBorderColor = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_selectedBorderColor;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_selectedBorderWidth = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_selectedBorderWidth;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_selectedItemOffset = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_selectedItemOffset;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_selectedItemPosition = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_selectedItemPosition;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_selectionMode = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_selectionMode;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_sliceBorderWidth = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_sliceBorderWidth;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_startAngle = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_startAngle;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_updateAnimation_duration = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_updateAnimation_duration;
			global::Xuni.Forms.FlexPie.Platform.Android.Resource.Styleable.FlexPie_flexPie_updateAnimation_startDelay = global::FlexPieDemo.Droid.Resource.Styleable.FlexPie_flexPie_updateAnimation_startDelay;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f09000f
			public const int flexPieCerulanPalette = 2131296271;
			
			// aapt resource value: 0x7f090001
			public const int flexPieCocoaPalette = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int flexPieCoralPalette = 2131296258;
			
			// aapt resource value: 0x7f09000b
			public const int flexPieCyborgPalette = 2131296267;
			
			// aapt resource value: 0x7f090003
			public const int flexPieDarkPalette = 2131296259;
			
			// aapt resource value: 0x7f09000e
			public const int flexPieDarklyPalette = 2131296270;
			
			// aapt resource value: 0x7f090000
			public const int flexPieDefaultflexPiePalette = 2131296256;
			
			// aapt resource value: 0x7f09000d
			public const int flexPieFlatlyPalette = 2131296269;
			
			// aapt resource value: 0x7f090004
			public const int flexPieHighConstrastPalette = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int flexPieLightPalette = 2131296261;
			
			// aapt resource value: 0x7f090010
			public const int flexPieMaterialPalette = 2131296272;
			
			// aapt resource value: 0x7f090006
			public const int flexPieMidnightPalette = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int flexPieMinimalPalette = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int flexPieModernPalette = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int flexPieOrganicPalette = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int flexPieSlatePalette = 2131296266;
			
			// aapt resource value: 0x7f09000c
			public const int flexPieSuperheroPalette = 2131296268;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010024
			public const int flexPie_animated = 2130772004;
			
			// aapt resource value: 0x7f01000e
			public const int flexPie_backgroundColor = 2130771982;
			
			// aapt resource value: 0x7f010022
			public const int flexPie_binding = 2130772002;
			
			// aapt resource value: 0x7f010021
			public const int flexPie_bindingName = 2130772001;
			
			// aapt resource value: 0x7f01000f
			public const int flexPie_borderColor = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int flexPie_borderWidth = 2130771984;
			
			// aapt resource value: 0x7f01001d
			public const int flexPie_datalabel_FontColor = 2130771997;
			
			// aapt resource value: 0x7f01001e
			public const int flexPie_datalabel_FontSize = 2130771998;
			
			// aapt resource value: 0x7f01001f
			public const int flexPie_datalabel_FontTypeface = 2130771999;
			
			// aapt resource value: 0x7f010020
			public const int flexPie_datalabel_FontWeight = 2130772000;
			
			// aapt resource value: 0x7f01001a
			public const int flexPie_datalabel_backgroundColor = 2130771994;
			
			// aapt resource value: 0x7f01001b
			public const int flexPie_datalabel_borderColor = 2130771995;
			
			// aapt resource value: 0x7f01001c
			public const int flexPie_datalabel_borderWidth = 2130771996;
			
			// aapt resource value: 0x7f010035
			public const int flexPie_datalabel_position = 2130772021;
			
			// aapt resource value: 0x7f01000a
			public const int flexPie_footer = 2130771978;
			
			// aapt resource value: 0x7f01000d
			public const int flexPie_footerFontColor = 2130771981;
			
			// aapt resource value: 0x7f010003
			public const int flexPie_footerFontGravity = 2130771971;
			
			// aapt resource value: 0x7f01000b
			public const int flexPie_footerFontSize = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int flexPie_footerFontTypeface = 2130771980;
			
			// aapt resource value: 0x7f010002
			public const int flexPie_footerFontWeight = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int flexPie_header = 2130771974;
			
			// aapt resource value: 0x7f010009
			public const int flexPie_headerFontColor = 2130771977;
			
			// aapt resource value: 0x7f010001
			public const int flexPie_headerFontGravity = 2130771969;
			
			// aapt resource value: 0x7f010007
			public const int flexPie_headerFontSize = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int flexPie_headerFontTypeface = 2130771976;
			
			// aapt resource value: 0x7f010000
			public const int flexPie_headerFontWeight = 2130771968;
			
			// aapt resource value: 0x7f010023
			public const int flexPie_innerRadius = 2130772003;
			
			// aapt resource value: 0x7f010017
			public const int flexPie_legend_FontColor = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int flexPie_legend_FontSize = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int flexPie_legend_FontTypeface = 2130771993;
			
			// aapt resource value: 0x7f010004
			public const int flexPie_legend_FontWeight = 2130771972;
			
			// aapt resource value: 0x7f010014
			public const int flexPie_legend_backgroundColor = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int flexPie_legend_borderColor = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int flexPie_legend_borderWidth = 2130771990;
			
			// aapt resource value: 0x7f01002c
			public const int flexPie_legend_orientation = 2130772012;
			
			// aapt resource value: 0x7f01002d
			public const int flexPie_legend_position = 2130772013;
			
			// aapt resource value: 0x7f01002f
			public const int flexPie_loadAnimation_duration = 2130772015;
			
			// aapt resource value: 0x7f01002e
			public const int flexPie_loadAnimation_loadAnimationMode = 2130772014;
			
			// aapt resource value: 0x7f010030
			public const int flexPie_loadAnimation_startDelay = 2130772016;
			
			// aapt resource value: 0x7f010027
			public const int flexPie_offset = 2130772007;
			
			// aapt resource value: 0x7f010005
			public const int flexPie_palette = 2130771973;
			
			// aapt resource value: 0x7f010011
			public const int flexPie_plotAreabackgroundColor = 2130771985;
			
			// aapt resource value: 0x7f010028
			public const int flexPie_reversed = 2130772008;
			
			// aapt resource value: 0x7f010033
			public const int flexPie_selectAnimation_duration = 2130772019;
			
			// aapt resource value: 0x7f010034
			public const int flexPie_selectAnimation_startDelay = 2130772020;
			
			// aapt resource value: 0x7f010012
			public const int flexPie_selectedBorderColor = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int flexPie_selectedBorderWidth = 2130771987;
			
			// aapt resource value: 0x7f010029
			public const int flexPie_selectedItemOffset = 2130772009;
			
			// aapt resource value: 0x7f01002a
			public const int flexPie_selectedItemPosition = 2130772010;
			
			// aapt resource value: 0x7f01002b
			public const int flexPie_selectionMode = 2130772011;
			
			// aapt resource value: 0x7f010025
			public const int flexPie_sliceBorderWidth = 2130772005;
			
			// aapt resource value: 0x7f010026
			public const int flexPie_startAngle = 2130772006;
			
			// aapt resource value: 0x7f010031
			public const int flexPie_updateAnimation_duration = 2130772017;
			
			// aapt resource value: 0x7f010032
			public const int flexPie_updateAnimation_startDelay = 2130772018;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f080000
			public const int defaultFlexPieAnimated = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int defaultFlexPieReversed = 2131230721;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060002
			public const int defaultFlexPieBorderWidth = 2131099650;
			
			// aapt resource value: 0x7f060007
			public const int defaultFlexPieDatalabel_FontSize = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int defaultFlexPieDatalabel_borderWidth = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int defaultFlexPieFooterFontSize = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int defaultFlexPieHeaderFontSize = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int defaultFlexPieInnerRadius = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int defaultFlexPieLegend_FontSize = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int defaultFlexPieLegend_borderWidth = 2131099652;
			
			// aapt resource value: 0x7f06000b
			public const int defaultFlexPieOffset = 2131099659;
			
			// aapt resource value: 0x7f060003
			public const int defaultFlexPieSelectedBorderWidth = 2131099651;
			
			// aapt resource value: 0x7f06000c
			public const int defaultFlexPieSelectedItemOffset = 2131099660;
			
			// aapt resource value: 0x7f060009
			public const int defaultFlexPieSliceBorderWidth = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int defaultFlexPieStartAngle = 2131099658;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int dct = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_launcher = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a000f
			public const int ALL = 2131361807;
			
			// aapt resource value: 0x7f0a0007
			public const int AUTO = 2131361799;
			
			// aapt resource value: 0x7f0a0000
			public const int BOLD = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int BOLD_ITALIC = 2131361793;
			
			// aapt resource value: 0x7f0a0008
			public const int BOTTOM = 2131361800;
			
			// aapt resource value: 0x7f0a0010
			public const int CENTER = 2131361808;
			
			// aapt resource value: 0x7f0a0004
			public const int CENTER_HORIZONTAL = 2131361796;
			
			// aapt resource value: 0x7f0a000d
			public const int HORIZONTAL = 2131361805;
			
			// aapt resource value: 0x7f0a0011
			public const int INSIDE = 2131361809;
			
			// aapt resource value: 0x7f0a0002
			public const int ITALIC = 2131361794;
			
			// aapt resource value: 0x7f0a0005
			public const int LEFT = 2131361797;
			
			// aapt resource value: 0x7f0a0009
			public const int NONE = 2131361801;
			
			// aapt resource value: 0x7f0a0003
			public const int NORMAL = 2131361795;
			
			// aapt resource value: 0x7f0a0012
			public const int OUTSIDE = 2131361810;
			
			// aapt resource value: 0x7f0a000b
			public const int POINT = 2131361803;
			
			// aapt resource value: 0x7f0a0006
			public const int RIGHT = 2131361798;
			
			// aapt resource value: 0x7f0a000c
			public const int SERIES = 2131361804;
			
			// aapt resource value: 0x7f0a000a
			public const int TOP = 2131361802;
			
			// aapt resource value: 0x7f0a000e
			public const int VERTICAL = 2131361806;
			
			// aapt resource value: 0x7f0a0014
			public const int tooltipContent = 2131361812;
			
			// aapt resource value: 0x7f0a0013
			public const int tooltipTitle = 2131361811;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070011
			public const int defaultFlexPieDatalabelPosition = 2131165201;
			
			// aapt resource value: 0x7f070005
			public const int defaultFlexPieDatalabel_FontWeight = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int defaultFlexPieFooterFontGravity = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int defaultFlexPieFooterFontWeight = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int defaultFlexPieHeaderFontGravity = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int defaultFlexPieHeaderFontWeight = 2131165184;
			
			// aapt resource value: 0x7f070008
			public const int defaultFlexPieLegendOrientation = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int defaultFlexPieLegendPosition = 2131165193;
			
			// aapt resource value: 0x7f070004
			public const int defaultFlexPieLegend_FontWeight = 2131165188;
			
			// aapt resource value: 0x7f07000b
			public const int defaultFlexPieLoadAnimationDuration = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int defaultFlexPieLoadAnimationMode = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int defaultFlexPieLoadAnimationStartDelay = 2131165196;
			
			// aapt resource value: 0x7f07000f
			public const int defaultFlexPieSelectAnimationDuration = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int defaultFlexPieSelectAnimationStartDelay = 2131165200;
			
			// aapt resource value: 0x7f070006
			public const int defaultFlexPieSelectedItemPosition = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int defaultFlexPieSelectionMode = 2131165191;
			
			// aapt resource value: 0x7f07000d
			public const int defaultFlexPieUpdateAnimationDuration = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int defaultFlexPieUpdateAnimationStartDelay = 2131165198;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int tooltip = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int defaultFlexPieDatalabel_FontTypeface = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int defaultFlexPieFooterFontTypeface = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int defaultFlexPieHeaderFontTypeface = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int defaultFlexPieLegend_FontTypeface = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int AppBaseTheme = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int AppTheme = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FlexPie = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016,
					2130772017,
					2130772018,
					2130772019,
					2130772020,
					2130772021};
			
			// aapt resource value: 36
			public const int FlexPie_flexPie_animated = 36;
			
			// aapt resource value: 14
			public const int FlexPie_flexPie_backgroundColor = 14;
			
			// aapt resource value: 34
			public const int FlexPie_flexPie_binding = 34;
			
			// aapt resource value: 33
			public const int FlexPie_flexPie_bindingName = 33;
			
			// aapt resource value: 15
			public const int FlexPie_flexPie_borderColor = 15;
			
			// aapt resource value: 16
			public const int FlexPie_flexPie_borderWidth = 16;
			
			// aapt resource value: 29
			public const int FlexPie_flexPie_datalabel_FontColor = 29;
			
			// aapt resource value: 30
			public const int FlexPie_flexPie_datalabel_FontSize = 30;
			
			// aapt resource value: 31
			public const int FlexPie_flexPie_datalabel_FontTypeface = 31;
			
			// aapt resource value: 32
			public const int FlexPie_flexPie_datalabel_FontWeight = 32;
			
			// aapt resource value: 26
			public const int FlexPie_flexPie_datalabel_backgroundColor = 26;
			
			// aapt resource value: 27
			public const int FlexPie_flexPie_datalabel_borderColor = 27;
			
			// aapt resource value: 28
			public const int FlexPie_flexPie_datalabel_borderWidth = 28;
			
			// aapt resource value: 53
			public const int FlexPie_flexPie_datalabel_position = 53;
			
			// aapt resource value: 10
			public const int FlexPie_flexPie_footer = 10;
			
			// aapt resource value: 13
			public const int FlexPie_flexPie_footerFontColor = 13;
			
			// aapt resource value: 3
			public const int FlexPie_flexPie_footerFontGravity = 3;
			
			// aapt resource value: 11
			public const int FlexPie_flexPie_footerFontSize = 11;
			
			// aapt resource value: 12
			public const int FlexPie_flexPie_footerFontTypeface = 12;
			
			// aapt resource value: 2
			public const int FlexPie_flexPie_footerFontWeight = 2;
			
			// aapt resource value: 6
			public const int FlexPie_flexPie_header = 6;
			
			// aapt resource value: 9
			public const int FlexPie_flexPie_headerFontColor = 9;
			
			// aapt resource value: 1
			public const int FlexPie_flexPie_headerFontGravity = 1;
			
			// aapt resource value: 7
			public const int FlexPie_flexPie_headerFontSize = 7;
			
			// aapt resource value: 8
			public const int FlexPie_flexPie_headerFontTypeface = 8;
			
			// aapt resource value: 0
			public const int FlexPie_flexPie_headerFontWeight = 0;
			
			// aapt resource value: 35
			public const int FlexPie_flexPie_innerRadius = 35;
			
			// aapt resource value: 23
			public const int FlexPie_flexPie_legend_FontColor = 23;
			
			// aapt resource value: 24
			public const int FlexPie_flexPie_legend_FontSize = 24;
			
			// aapt resource value: 25
			public const int FlexPie_flexPie_legend_FontTypeface = 25;
			
			// aapt resource value: 4
			public const int FlexPie_flexPie_legend_FontWeight = 4;
			
			// aapt resource value: 20
			public const int FlexPie_flexPie_legend_backgroundColor = 20;
			
			// aapt resource value: 21
			public const int FlexPie_flexPie_legend_borderColor = 21;
			
			// aapt resource value: 22
			public const int FlexPie_flexPie_legend_borderWidth = 22;
			
			// aapt resource value: 44
			public const int FlexPie_flexPie_legend_orientation = 44;
			
			// aapt resource value: 45
			public const int FlexPie_flexPie_legend_position = 45;
			
			// aapt resource value: 47
			public const int FlexPie_flexPie_loadAnimation_duration = 47;
			
			// aapt resource value: 46
			public const int FlexPie_flexPie_loadAnimation_loadAnimationMode = 46;
			
			// aapt resource value: 48
			public const int FlexPie_flexPie_loadAnimation_startDelay = 48;
			
			// aapt resource value: 39
			public const int FlexPie_flexPie_offset = 39;
			
			// aapt resource value: 5
			public const int FlexPie_flexPie_palette = 5;
			
			// aapt resource value: 17
			public const int FlexPie_flexPie_plotAreabackgroundColor = 17;
			
			// aapt resource value: 40
			public const int FlexPie_flexPie_reversed = 40;
			
			// aapt resource value: 51
			public const int FlexPie_flexPie_selectAnimation_duration = 51;
			
			// aapt resource value: 52
			public const int FlexPie_flexPie_selectAnimation_startDelay = 52;
			
			// aapt resource value: 18
			public const int FlexPie_flexPie_selectedBorderColor = 18;
			
			// aapt resource value: 19
			public const int FlexPie_flexPie_selectedBorderWidth = 19;
			
			// aapt resource value: 41
			public const int FlexPie_flexPie_selectedItemOffset = 41;
			
			// aapt resource value: 42
			public const int FlexPie_flexPie_selectedItemPosition = 42;
			
			// aapt resource value: 43
			public const int FlexPie_flexPie_selectionMode = 43;
			
			// aapt resource value: 37
			public const int FlexPie_flexPie_sliceBorderWidth = 37;
			
			// aapt resource value: 38
			public const int FlexPie_flexPie_startAngle = 38;
			
			// aapt resource value: 49
			public const int FlexPie_flexPie_updateAnimation_duration = 49;
			
			// aapt resource value: 50
			public const int FlexPie_flexPie_updateAnimation_startDelay = 50;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
