//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexChartDemo.Data.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlexChartDemo.Data.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Point.
        /// </summary>
        public static string AddPoint {
            get {
                return ResourceManager.GetString("AddPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the basic chart types and stacking options..
        /// </summary>
        public static string BasicChartTypesDescription {
            get {
                return ResourceManager.GetString("BasicChartTypesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Chart Types.
        /// </summary>
        public static string BasicChartTypesTitle {
            get {
                return ResourceManager.GetString("BasicChartTypesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a bubble chart..
        /// </summary>
        public static string BubbleChartDescription {
            get {
                return ResourceManager.GetString("BubbleChartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bubble Chart.
        /// </summary>
        public static string BubbleChartTitle {
            get {
                return ResourceManager.GetString("BubbleChartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows conditional formatting by customizing plot elements..
        /// </summary>
        public static string ConditionalFormattingDescription {
            get {
                return ResourceManager.GetString("ConditionalFormattingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditional Formatting.
        /// </summary>
        public static string ConditionalFormattingTitle {
            get {
                return ResourceManager.GetString("ConditionalFormattingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows customized axis style and label format..
        /// </summary>
        public static string CustomizingAxesDescription {
            get {
                return ResourceManager.GetString("CustomizingAxesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customizing Axes.
        /// </summary>
        public static string CustomizingAxesTitle {
            get {
                return ResourceManager.GetString("CustomizingAxesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to fully customize plot elements..
        /// </summary>
        public static string CustomPlotElementsDescription {
            get {
                return ResourceManager.GetString("CustomPlotElementsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Plot Elements.
        /// </summary>
        public static string CustomPlotElementsTitle {
            get {
                return ResourceManager.GetString("CustomPlotElementsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a customized tooltip..
        /// </summary>
        public static string CustomTooltipsDescription {
            get {
                return ResourceManager.GetString("CustomTooltipsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Tooltips.
        /// </summary>
        public static string CustomTooltipsTitle {
            get {
                return ResourceManager.GetString("CustomTooltipsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a simple chart with static data labels..
        /// </summary>
        public static string DataLabelsDescription {
            get {
                return ResourceManager.GetString("DataLabelsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Labels.
        /// </summary>
        public static string DataLabelsTitle {
            get {
                return ResourceManager.GetString("DataLabelsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a dynamic, “live” chart..
        /// </summary>
        public static string DynamicChartDescription {
            get {
                return ResourceManager.GetString("DynamicChartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic Charts.
        /// </summary>
        public static string DynamicChartTitle {
            get {
                return ResourceManager.GetString("DynamicChartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to export an image of FlexChart..
        /// </summary>
        public static string ExportImageDescription {
            get {
                return ResourceManager.GetString("ExportImageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Image.
        /// </summary>
        public static string ExportImageTitle {
            get {
                return ResourceManager.GetString("ExportImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows stock data in a candle chart..
        /// </summary>
        public static string FinancialChartDescription {
            get {
                return ResourceManager.GetString("FinancialChartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Chart.
        /// </summary>
        public static string FinancialChartTitle {
            get {
                return ResourceManager.GetString("FinancialChartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a simple chart with tooltips..
        /// </summary>
        public static string GettingStartedDescription {
            get {
                return ResourceManager.GetString("GettingStartedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Started.
        /// </summary>
        public static string GettingStartedTitle {
            get {
                return ResourceManager.GetString("GettingStartedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrates use of the FlexChart&apos;s hitTest method..
        /// </summary>
        public static string HitTestDescription {
            get {
                return ResourceManager.GetString("HitTestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit Test.
        /// </summary>
        public static string HitTestTitle {
            get {
                return ResourceManager.GetString("HitTestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows basic chart headers and axis titles..
        /// </summary>
        public static string LegendSampleDescription {
            get {
                return ResourceManager.GetString("LegendSampleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend and Titles.
        /// </summary>
        public static string LegendSampleTitle {
            get {
                return ResourceManager.GetString("LegendSampleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showss animation modes when data is loaded..
        /// </summary>
        public static string LoadAnimationDescription {
            get {
                return ResourceManager.GetString("LoadAnimationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Animation Mode.
        /// </summary>
        public static string LoadAnimationTitle {
            get {
                return ResourceManager.GetString("LoadAnimationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a composite chart..
        /// </summary>
        public static string MixedChartTypesDescription {
            get {
                return ResourceManager.GetString("MixedChartTypesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixed Chart Types.
        /// </summary>
        public static string MixedChartTypesTitle {
            get {
                return ResourceManager.GetString("MixedChartTypesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a chart with mutiple Y axes..
        /// </summary>
        public static string MultipleAxesDescription {
            get {
                return ResourceManager.GetString("MultipleAxesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Axes.
        /// </summary>
        public static string MultipleAxesTitle {
            get {
                return ResourceManager.GetString("MultipleAxesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Point.
        /// </summary>
        public static string RemovePoint {
            get {
                return ResourceManager.GetString("RemovePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a chart with panning (or scrolling) along the axes..
        /// </summary>
        public static string ScrollingDescription {
            get {
                return ResourceManager.GetString("ScrollingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrolling.
        /// </summary>
        public static string ScrollingTitle {
            get {
                return ResourceManager.GetString("ScrollingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag to scroll/Pinch to zoom.
        /// </summary>
        public static string ScrollZoomInstructions {
            get {
                return ResourceManager.GetString("ScrollZoomInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the different selection modes..
        /// </summary>
        public static string SelectionModesDescription {
            get {
                return ResourceManager.GetString("SelectionModesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Modes.
        /// </summary>
        public static string SelectionModesTitle {
            get {
                return ResourceManager.GetString("SelectionModesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows customized series styling..
        /// </summary>
        public static string StylingSeriesDescription {
            get {
                return ResourceManager.GetString("StylingSeriesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styling Series.
        /// </summary>
        public static string StylingSeriesTitle {
            get {
                return ResourceManager.GetString("StylingSeriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the built-in palettes..
        /// </summary>
        public static string ThemingDescription {
            get {
                return ResourceManager.GetString("ThemingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theming.
        /// </summary>
        public static string ThemingTitle {
            get {
                return ResourceManager.GetString("ThemingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the ability to toggle a series visibility..
        /// </summary>
        public static string ToggleSeriesDescription {
            get {
                return ResourceManager.GetString("ToggleSeriesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Series.
        /// </summary>
        public static string ToggleSeriesTitle {
            get {
                return ResourceManager.GetString("ToggleSeriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows animation when data is updated..
        /// </summary>
        public static string UpdateAnimationDescription {
            get {
                return ResourceManager.GetString("UpdateAnimationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Animation.
        /// </summary>
        public static string UpdateAnimationTitle {
            get {
                return ResourceManager.GetString("UpdateAnimationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows stretch zoom-out and pinch zoom-in gestures..
        /// </summary>
        public static string ZoomingScrollingDescription {
            get {
                return ResourceManager.GetString("ZoomingScrollingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zooming and Scrolling.
        /// </summary>
        public static string ZoomingScrollingTitle {
            get {
                return ResourceManager.GetString("ZoomingScrollingTitle", resourceCulture);
            }
        }
    }
}
